### ISSUE TITLE
Small example on how to use?

### ISSUE THREAD

**Issue by Whoaa512** [Kononnable/typeorm-model-generator#1]
Would love to run this to get up and going with typeorm and my existing Postgres data.

Could you write up a short example for the readme?

**Comment by Kononnable** [comment]
You would have to wait few weeks - there is no postgres support yet.

Right now it works only with mssql and still got few big issues. After I fix them I will add support for more database engines(starting with postgres and mysql).
I think postgres support would be ready in about 3-4 weeks from now.
    
__
Right now command for creating typeorm model files from existing mssql db looks like:
`node .\src\index.js -h localhost -d dbName -u user -x password` 

All command arguments can be listed by running `node .\src\index.js` in the repo root directory.

**Comment by destinatus** [comment]
[14:43:40] Starting creation of model classes.
(node:10632) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ORA-00904: "IDENTITY_COLUMN": invalid identifier
(node:10632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Connecting to Oracle database.
Oracledb and Instant Client are installed.
