### ISSUE TITLE
Column types missing, class member access control

### ISSUE THREAD

**Issue by btxtiger** [Kononnable/typeorm-model-generator#108]
I generated models from MySQL database and got some issues (not sure if I really should create multiple github issues).
```ts
   @PrimaryGeneratedColumn({
      name: 'log_id',
   })
   logId: string;
```

- Primary column `log_id` should be BIGINT and UNSIGNED. Both values were not included.
- Additionally it would be nice to have an option to generate class members with explicit access declaration, because users of tslint rule `'member-access': true` will get errors here.
Means `public logId: string;` instead of  just `logId: string`
- `{ onDelete: 'NO ACTION', onUpdate: 'NO ACTION'}` were always generated, not sure if this is really necessary, because it is the default action for MySQL.
- `@Colum('datetime')` was generated with config prop: `default: 'CURRENT_TIMESTAMP',`
but this pattern does not work, it needs to be `default: () => 'CURRENT_TIMESTAMP',`
- For regular columns with unsigned bigint ` @Column('bigint', {` was generated instead ` @Column('unsigned big int', {` 
EDIT: 'unsigned big int' seems to be not accepted for mysql, I'm not sure why
- Generating a jsdoc comment above each class and column would heavily increase readability. Just put the class/col name in there
- It might be useful to include formatting with prettier, which can correct missing spaces, newlines etc. and tslint autofixer to remove unused imports.

- The column is not nullable, so the Promise should not be able to be type of `null`
```ts
   @ManyToOne(type => User, { nullable: false })
   @JoinColumn({ name: 'of_user_modified' })
   public ofUserModified: Promise<User | null>;
```

**Comment by Kononnable** [comment]
> Primary column log_id should be BIGINT and UNSIGNED. Both values were not included.
I've added type(bigint) for generated `@PrimaryGeneratedColumn` decorator. Didn't push version to npm yet.

>EDIT: 'unsigned big int' seems to be not accepted for mysql, I'm not sure why
Type seen by typeorm is bigint, unsigned should be set in options.

I was planning on implementing some of issues you mentioned here(like not generating default values), but currently don't have enough time for that.

**Comment by Kononnable** [comment]
Looks like everything from here(except for jsdocs) was implemented/addressed in some other way.
As for jsdocs if someone wants to implement this it should be easy to create PR for it. I won't implement this myself(at least for now) - I'm uncertain of the design(what exactly should go to jsdocs comments) to make such comments usefull.
