### ISSUE TITLE
How to let it work each day ?

### ISSUE THREAD

**Issue by pairmix** [Kononnable/typeorm-model-generator#114]
Hi there,
Sometimes, work , more often doesn't.
2 hours ago, it worked but now it doesn't.
Tried with windows 7 and windows 10:

λ npx typeorm-model-generator -h localhost -d pairmix -p 3305 -u root -x admin -e mariadb -o D:\Applications\api\models
npx: installed 1 in 1.72s
Path must be a string. Received undefined
null
npx: installed 1 in 1.704s
Path must be a string. Received undefined
null
npx: installed 1 in 1.718s
Path must be a string. Received undefined
null
npx: installed 1 in 1.695s
Path must be a string. Received undefined
null
npx: installed 1 in 1.657s
Path must be a string. Received undefined
null
npx: installed 1 in 1.842s
Path must be a string. Received undefined
null
npx: installed 1 in 1.764s
Path must be a string. Received undefined
null
npx: installed 1 in 1.727s
Path must be a string. Received undefined
null
npx: installed 1 in 1.666s
Path must be a string. Received undefined
null
npx: installed 1 in 1.692s
Path must be a string. Received undefined
null
npx: installed 1 in 1.737s
Path must be a string. Received undefined
null
npx: installed 1 in 1.75s
Path must be a string. Received undefined
null
npx: installed 1 in 1.762s
Path must be a string. Received undefined
null

**Comment by Kononnable** [comment]
Looks like npx on windows issue https://github.com/zkat/npx/issues/144
Read through the issue - there is solution how to fix it.
