### ISSUE TITLE
[QUESTIONS]: CamelCase and server side - client side entities

### ISSUE THREAD

**Issue by pairmix** [Kononnable/typeorm-model-generator#118]
Hi there, i have to questions:
1- How to generate classes and file name with upper case ?
npx typeorm-model-generator -h localhost -d db -p 3305 -u root -x admin -e mariadb -o C:\Applications\Node\AWS\api\models --cf camel --ce camel  --cp camel does not do that stuff.

2 - How to use these server side generated classes into my ionic application?
Currently, i have 2 folders (1 server side and 1 client side) and i have to report manually all changes from my server side folder into my client side folder. That's not the solution i suppose.

Thanks in advance.

**Comment by Kononnable** [comment]
1) I think you're looking for PascalCase not camelCase `--cf pascal`
2) You should search for it in typeorm repo(I think there were similar questions with answers) or ask on typeorm slack chat.One solution will be to put entities definitions on same level as both apps and import same files from two projects - but I'm not using ionic with typeorm on daily basis, so I'm not an expert in that area.

**Comment by pairmix** [comment]
Thank you very much @Kononnable , i didn't know PascalCase.
My last question: is there any way to prevent schema attribute generation because my schema is not the same in my environments dev, staging and prod.

@Entity("adresse",{schema:"my_schema_dev"})

Best regards

**Comment by pairmix** [comment]
Thank you @Kononnable !

**Comment by kaibadash** [comment]
I converted with a disposable code 😅.
https://gist.github.com/kaibadash/8a44be31e75ee43a2acc44866832329f
