### ISSUE TITLE
error TS2345: Argument of type '{ nullable: false; onDelete: "RESTRICT"; onUpdate: string; }' is not assignable to parameter of type 'RelationOptions'.

### ISSUE THREAD

**Issue by pairmix** [Kononnable/typeorm-model-generator#119]
Hi there,
My generated entities cannot compile:

C:/Applications/Node/AWS/api/src/entity/Article.ts(21,129): error TS2345: Argument of type '{ nullable: false; onDelete: "RESTRICT"; onUpdate: string; }' is not assignable to parameter of type 'RelationOptions'.

**Comment by Kononnable** [comment]
Sorry for long delay. I didn't have a lot of time for OSS lately. Can you provide some reproduction data(DDL statements)? I tried to reproduce the issue, but didn't succeed.

**Comment by Maxpain177** [comment]
@Kononnable,  it's typeorm@next

**Comment by Kononnable** [comment]
Closing as no response from the author.
