### ISSUE TITLE
Generation of Duplicate Identifier

### ISSUE THREAD

**Issue by Joniras** [Kononnable/typeorm-model-generator#12]
This was generated for me:

```typescript
    @OneToMany(type=>product_detail, product_details=>product_details.fproduct_seq_id)
    product_details:product_detail[];



    @OneToMany(type=>product_detail, product_details=>product_details.fproduct_consist_seq_id)
    product_details:product_detail[];
```

which gave me the error: duplicate identifier 'product_details'
Due to more than one OneToMany Relations the names do not differ and Typescript gives an Error.
I found that the Error was in the MysqlDriver.ts:301, when the name is created: 
```typescript
col.name = ownerEntity.EntityName.toLowerCase() + 's'
```
This should be chosen different.

Thanks for any help.

More Infos:
TypeORM: 0.1.6
TypeORM-Model-Generator: 0.2.2
NPM Version: 5.5.1
Node Version: 9.2.0
Used Database: MySQL
Used Mysql-Package:  2.15.0

**Comment by Kononnable** [comment]
Fixed

**Comment by Joniras** [comment]
actually, 10 references where not enough for me. i needed 14...
Maybe put 20 instead of 10 just to be sure ?
But thank you so much for fixing it.
