### ISSUE TITLE
Ignore tables parameter

### ISSUE THREAD

**Issue by d0whc3r** [Kononnable/typeorm-model-generator#120]
A new feature to ignore tables, could be useful for databases which are versioned using liquibase.
Then in parameters could be:
`typeorm-model-generator -h localhost -d tempdb -u sa -x !Passw0rd -e mysql -o . --ignore "DATABASECHANGELOG,DATABASECHANGELOGLOCK"`

Where `DATABASECHANGELOG` and `DATABASECHANGELOGLOCK` are autogenerated tables by liquibase and there is no need to generate entities of them

**Comment by cooljeffro** [comment]
You could create a user for your database that doesn't have access to those tables.  Then use that user when generating the models.

**Comment by Kononnable** [comment]
Implemented in `typeorm-model-generator@0.4.0`
