### ISSUE TITLE
Guidance on when to use lazy relations

### ISSUE THREAD

**Issue by ndarilek** [Kononnable/typeorm-model-generator#129]
There isn't much of an explanation of this in the README. It looks like lazy relations generate `Promise<Type | null>`, which on one hand I like because it seems cleaner to explicitly await the resolution of a relation rather than figuring out another ORM-specific syntax for when to load what relations.

On the other hand, maybe everything gets queried regardless, even if I don't resolve the promises, so maybe I'm still hitting my database with potentially unused relation queries. And this does seem to complicate things in the case where I'd like to query for a specific model, then serialize the result and needed relations to JSON.

Did I make a mistake using this option? If so, I can manually drop the promises from my converted code, though if the potential pitfalls I've identified above aren't that big, then I'll keep things as they are.

Thanks for a great piece of software!

**Comment by Kononnable** [comment]
In typeorm every relation which doesn't have `eager:true` in it options won't hit database unless you especially order it to be fetched.

I wouldn't recommend using lazy relations right now. They're marked as experimental in typeorm and might change in the future. There are some flows in its design and this feature might be even deleted at all. Some parts of discussion about that is here typeorm/typeorm#2966

Personally I don't use typeorm(I'm not working on any project which would require usage of ORM in NodeJs), so I'm not the best person to be a judge which way is best to fetch relational data. You should ask a question on typeorm slack channel or make an issue in the repo. Some folks which are using typeorm daily are active there, so can tell which works for them best

**Comment by ndarilek** [comment]
Thanks for the context. Didn't see anything obvious in the TypeORM docs 
about this feature, so thought it was specific to the model generator. 
I'll check out the issue thread.
