### ISSUE TITLE
Duplicate identifier

### ISSUE THREAD

**Issue by CatsMiaow** [Kononnable/typeorm-model-generator#130]
node_modules
- Node.js: v8.11.2
- mysql: ^2.16.0
- typeorm: ^0.2.9
- typeorm-model-generator: ^0.2.22

beds.ts
**error TS2300: Duplicate identifier 'room_'.**
<img width="829" alt="2018-12-14 2 17 36" src="https://user-images.githubusercontent.com/1300172/49984403-35afbc00-ffab-11e8-8109-61f3049da781.png">

rooms.ts
<img width="806" alt="2018-12-14 2 29 36" src="https://user-images.githubusercontent.com/1300172/49984740-b3c09280-ffac-11e8-85e7-5d4ac8a9c33a.png">

```sql
CREATE TABLE `beds` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `roomtype_id` int(11) unsigned DEFAULT NULL,
  `room_id` int(11) unsigned DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_bed_room_id` (`room_id`),
  KEY `index_bed_roomtype_id` (`roomtype_id`),
  CONSTRAINT `fk_room_bed` FOREIGN KEY (`room_id`) REFERENCES `rooms` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

CREATE TABLE `rooms` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `seq` smallint(5) unsigned DEFAULT '1',
  `roomtype_id` int(11) unsigned DEFAULT NULL,
  `name` varchar(128) NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_room_name` (`name`),
  KEY `index_room_roomtype_id` (`roomtype_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

**Comment by Kononnable** [comment]
I'm not reproducing issue on that DDL languages. Could you check `typeorm-model-ganerator@0.2.3`? There were some changes which might help.

**Comment by CatsMiaow** [comment]
The same problem occurs.

Create Database test
CREATE TABLE `rooms` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

CREATE TABLE `beds` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `room_id` int(11) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_bed_room_id` (`room_id`),
  CONSTRAINT `fk_room_bed` FOREIGN KEY (`room_id`) REFERENCES `rooms` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

**Comment by CatsMiaow** [comment]
MySQL Version: "5.7.12-log"
typeorm-model-generator: "^0.2.23"

```sql
CREATE DATABASE test;

CREATE TABLE `rooms` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

CREATE TABLE `beds` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `room_id` int(11) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_bed_room_id` (`room_id`),
  CONSTRAINT `fk_room_bed` FOREIGN KEY (`room_id`) REFERENCES `rooms` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

The same problem occurs.
https://github.com/Kononnable/typeorm-model-generator/blob/62c931883360c26c2b82ecfae90cd867b0c4f7c6/src/drivers/MysqlDriver.ts#L270
It seems to be generated as many as the result of the above query.

<img width="820" alt="2018-12-18 11 10 30" src="https://user-images.githubusercontent.com/1300172/50127721-a7427f80-02b5-11e9-90fa-bc71e317eab5.png">

Removing one as a test will not Duplicate identifier.

**Comment by Kononnable** [comment]
Sorry for long delay before response. I still get one relation generated for these DDL statements. I guess it's because of lack of some constraint.

Could you paste results of that query, but with every column(*) instead of selected ones? I need to find out why it is duplicating that row with change in `onUpdated` column. Probably something with a join condition but right now I don't have a clue what is missing.

**Comment by CatsMiaow** [comment]
CSV file format

```sql
SELECT
    *
FROM
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE CU
    JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC ON CU.CONSTRAINT_NAME = RC.CONSTRAINT_NAME
WHERE
    TABLE_SCHEMA = SCHEMA()
    AND CU.REFERENCED_TABLE_NAME IS NOT NULL;
```
Result1: [1.txt](https://github.com/Kononnable/typeorm-model-generator/files/2709199/1.txt)

```sql
SELECT
    *
FROM
    INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
WHERE
    CONSTRAINT_NAME = 'fk_room_bed';    
```
Result2: [2.txt](https://github.com/Kononnable/typeorm-model-generator/files/2709200/2.txt)

```sql
SELECT
    *
FROM
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE CU
    JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC
        ON CU.CONSTRAINT_NAME = RC.CONSTRAINT_NAME AND CU.CONSTRAINT_SCHEMA = RC.CONSTRAINT_SCHEMA
WHERE
    TABLE_SCHEMA = SCHEMA()
    AND CU.REFERENCED_TABLE_NAME IS NOT NULL;
```
Result3: [3.txt](https://github.com/Kononnable/typeorm-model-generator/files/2709201/3.txt)

It seems that the key(CONSTRAINT_NAME) names of other databases are output as duplicates.
In Result3, I added the following condition.
```sql
AND CU.CONSTRAINT_SCHEMA = RC.CONSTRAINT_SCHEMA
```

**Comment by Kononnable** [comment]
Thanks for catching that up. I was always running tests on docker container with only one database.

**Comment by Maxpain177** [comment]
Same issue on latest version of typeorm-model-generator

**Comment by Kononnable** [comment]
@Maxpain177 
Could you check what returns this query? **https://github.com/Kononnable/typeorm-model-generator/blob/75b6f62903c3440872e707b68ed0a1b5482aa431/src/drivers/PostgresDriver.ts#L456-L493**
If it returns many records for that relation we need to find out why is that.
Or you could share your DDL statements(if it's not a trade secret etc.) - I need something to reproduce the issue. Having two similar dbs on same server doesn't introduce the bug as it was in original issue.

**Comment by Maxpain177** [comment]
@Kononnable I've sent the result of this query to your email.

**Comment by Maxpain177** [comment]
@Kononnable 
DDL for `party_members`
```sql
-- DDL generated by Postico 1.5.4
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE party_members (
    party_id integer NOT NULL REFERENCES parties(id),
    user_id integer NOT NULL REFERENCES users(id),
    accepted boolean NOT NULL DEFAULT false,
    date timestamp with time zone NOT NULL DEFAULT now(),
    game_id smallint REFERENCES games(id)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX party_members_party_id_user_id_idx ON party_members(party_id int4_ops,user_id int4_ops);
```

DDL for `users`
```sql
-- DDL generated by Postico 1.5.4
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE users (
    id integer PRIMARY KEY,
    nick_name character varying(32) NOT NULL,
    first_name character varying(24),
    last_name character varying(24),
    birthday timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    phone character varying(15),
    email character varying(128),
    phone_confirmed boolean NOT NULL DEFAULT false,
    email_confirmed boolean NOT NULL DEFAULT false,
    last_activity timestamp with time zone NOT NULL DEFAULT now(),
    link character varying(32) UNIQUE,
    avatar character varying(32),
    gender users_gender,
    city_id integer REFERENCES cities(id),
    avatar_url character varying,
    friends_count smallint NOT NULL DEFAULT 0,
    unread_notifications_count integer NOT NULL DEFAULT 0,
    verified boolean NOT NULL DEFAULT false,
    fb_id bigint,
    vk_id integer,
    twitch_id integer,
    is_completed_registration boolean NOT NULL DEFAULT false,
    online boolean NOT NULL DEFAULT true,
    unread_messages_count integer NOT NULL DEFAULT 0,
    notification_last_read_at timestamp with time zone NOT NULL DEFAULT now(),
    prefer_region integer REFERENCES server_regions(id),
    auto_connect boolean NOT NULL DEFAULT false,
    receive_email_notifications boolean NOT NULL DEFAULT true,
    is_mobile boolean NOT NULL DEFAULT false,
    unread_dialogs_count integer NOT NULL DEFAULT 0,
    friends_invites_count integer NOT NULL DEFAULT 0,
    region_id smallint NOT NULL DEFAULT '1'::smallint REFERENCES regions(id)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX users_link_key ON users(link text_ops);
CREATE UNIQUE INDEX users_pkey ON users(id int4_ops);
CREATE INDEX users_first_name_idx ON users(first_name text_ops);
CREATE UNIQUE INDEX users_id_key ON users(id int4_ops);
CREATE INDEX users_last_name_idx ON users(last_name text_ops);
CREATE INDEX users_nick_name_idx ON users(nick_name text_ops);
CREATE INDEX users_online_idx ON users(online bool_ops);
CREATE INDEX users_created_at_idx ON users(created_at timestamptz_ops);
CREATE INDEX users_last_activity_idx ON users(last_activity timestamptz_ops);
```

**Comment by Kononnable** [comment]
@Maxpain177 
Thank you for sharing full schema. I was able to find out what was the reason.
PostgreSQL doesn't enforce constraint names to be unique within a schema and such situation was causing the bug in your case.
https://www.postgresql.org/docs/9.1/information-schema.html
