### ISSUE TITLE
Custom Class Name

### ISSUE THREAD

**Issue by zurez-sgig** [Kononnable/typeorm-model-generator#134]
The MSSQL table has dots in name.
The  generated class names also has dot in its name , which throws exception while compiling. 
Any way to implement custom class name?
PS: tried NamingStrategy but it doesn't affect class name.

**Comment by Kononnable** [comment]
`entityName()` changes names of generated classes. Tested it - it works(however there is a bug and it changes even entity decorator).

**Comment by Kononnable** [comment]
Fixed bug mentioned earlier in 0.2.25, so you should be able to use naming strategy to change generated entity names.

As for using it - you should copy `NamingStrategy.ts` from this repo, make changes to `entityName` function which will handle dots the way you like. Then just compile it. When you want to generate model pass aditional parameter `--namingStrategy=/path/to/your/custom/naming/strategy/file`.
