### ISSUE TITLE
Connecting to Oracle DB

### ISSUE THREAD

**Issue by kadarius0719** [Kononnable/typeorm-model-generator#138]
Hello,

I am having trouble trying to connect to an Oracle DB on a server. I installed the Oracle Client per the instructions, am using a tnsnames.ora file that works when trying to connect through DataGrip, and I also know the password and username are correct. However, I get this out put when trying to connect:

**PS C:\318\api> typeorm-model-generator -h oradbdev03.pnl.gov -d rexd.dev.pnnl -p 1521 -u "user here" -x "password here" -e oracle -o .
typeorm-model-generator@0.2.25
[14:47:24] Starting creation of model classes.
Error connecting to Oracle Server.
Error occured in typeorm-model-generator.
typeorm-model-generator@0.2.25  node@v8.12.0
If you think this is a bug please open an issue including this log on https://github.com/Kononnable/typeorm-model-generator/issues
ORA-01017: invalid username/password; logon denied
(node:17744) UnhandledPromiseRejectionWarning: Error: ORA-01017: invalid username/password; logon denied
(node:17744) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17744) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.**

When using the oracledb module in another project, I specify a "connectString" variable with the tnsnames.ora params I have, which I put here: C:\oracle\instantclient_18_3\network\admin. Do I need to specify that when using the CLI?

Has anyone had any luck with using the modeler with an Oracle DB, and if so can anyone point out possible issues that may be causing the error I am seeing.

**Comment by Kononnable** [comment]
Closing as no answer from the reporter.
