### ISSUE TITLE
Shadowed variables

### ISSUE THREAD

**Issue by Maxpain177** [Kononnable/typeorm-model-generator#141]
Please fix this for the tslint :)
![image](https://user-images.githubusercontent.com/5875582/51893956-817dbf80-23b7-11e9-9ac5-9c7d5b72c5b6.png)

**Comment by ekifox** [comment]
type => Cities, cities => cities.serverRegions(s)

**Comment by ekifox** [comment]
type => Cities, cities => cities.serverRegions

Cities already exists in outer scope.

**Comment by Kononnable** [comment]
Implemented and released in `typeorm-model-generator@0.3.2`
