### ISSUE TITLE
Multiple database support

### ISSUE THREAD

**Issue by bugkarma** [Kononnable/typeorm-model-generator#144]
**Feature request**

TypeORM supports multiple databases, but `typeorm-model-generator` only allows for one. This makes it unusable if you have cross-db foreign keys.

This is the error when trying to generate a model from a database that has a foreign key relation to another database:
`Relation between tables field and source didn't found entity model source.`

Here is the TypeORM reference for multiple connection support:
https://github.com/typeorm/typeorm/blob/master/docs/multiple-connections.md

**Comment by sheikalthaf** [comment]
@Kononnable thanks for this awesome library. please add this feature

**Comment by Kononnable** [comment]
Implemented and released in typeorm-model-generator@0.3.2

**Comment by sheikalthaf** [comment]
@Kononnable  Thanks for your great work 👏. will try this now
