### ISSUE TITLE
Fails due to missing fs-extra

### ISSUE THREAD

**Issue by dantman** [Kononnable/typeorm-model-generator#146]
Using `npx typeorm-model-generator` doesn't actually work, it fails with a `Cannot find module 'fs-extra'` error.

It appears that index.js requires `fs-extra` and `fs-extra` is defined in devDeps instead of deps so it's not installed.

**Comment by Kononnable** [comment]
Thanks for report. I was using fs-extra only in tests before, forgot to put them to dependencies in last release.
Published as `typeorm-model-generator@0.3.1`.
