### ISSUE TITLE
Mysql Enum Data Type Error

### ISSUE THREAD

**Issue by VirnectRemote** [Kononnable/typeorm-model-generator#147]
My Mysql Database have column which have enum data type .

```sql
email_confirm ENUM('Y','N') DEFAULT 'N'
```
Showing Following Error Message When Generate Typeorm Model

![image](https://user-images.githubusercontent.com/47239828/52697064-e63e3a00-2fb3-11e9-81c4-be9e147977be.png)

The Source Code Part is Follow
```javascript
                        case "enum":
                            colInfo.tsType = "string";
                            colInfo.options.enum = resp.column_type
                                .substring(5, resp.column_type.length - 1)
                                .replace(/\'/gi, '"');
                            break;
```

**Comment by Kononnable** [comment]
PR was merged so I think this should be closed some time ago.
