### ISSUE TITLE
JoinTables with autogenerated id column are not recognised as ManyToMany

### ISSUE THREAD

**Issue by baerrach** [Kononnable/typeorm-model-generator#149]
From http://typeorm.io/#/many-to-many-relations

Instead of this structure
```
+-------------+--------------+----------------------------+
|                   question_categories                   |
+-------------+--------------+----------------------------+
| questionId  | int(11)      | PRIMARY KEY FOREIGN KEY    |
| categoryId  | int(11)      | PRIMARY KEY FOREIGN KEY    |
+-------------+--------------+----------------------------+
```

We have an additional column that is the primary key for the join table.

The generator can't handle this.

My work around for now is to drop the column.

**Comment by Kononnable** [comment]
What do you mean by "can't handle this"? It generates OneToMany relations and junction entity?

**Comment by baerrach** [comment]
Yes, you are right, but in this case the intermediate junction entity is not needed.

So instead of generating an entity as per http://typeorm.io/#/many-to-many-relations

```
    @ManyToMany(type => Category)
    @JoinTable()
    categories: Category[];
```

It will instead generate a OneToMany relationship to the junction entity Questioncategory.
And the junction entity with have a OneToMany relationship to both Question and Category.

If you delete the auto-generated id, re-run the type generator then you get the correct results.

If the only other column is an auto-generated id I was wondering whether it should instead use a JoinTable instead of the Junction entity.

**Comment by Kononnable** [comment]
Typeorm ManyToMay relations doesn't allow junction tables to have any additional fields. There is no way to tell typeorm, that there is additional id field, so that's why it generates it this way.

I have no idea if defining such db model as ManyToMany relation would work(even if it's not officially supported). In some cases probably, but won't there be any hard to see bugs? Schema sync/migrations wouldn't work for sure, but that's not a big deal in some cases.

**Comment by baerrach** [comment]
Fair enough, we are still new to TypeORM and only really using it as DB -> Entity classes.

We then manually tweak the classes (applying cascade:true, or name options), and re-apply those changes each time we regenerate.
