### ISSUE TITLE
Postgres `varchar(255)` printed as "character varying"

### ISSUE THREAD

**Issue by vjpr** [Kononnable/typeorm-model-generator#15]
Makes it kind of verbose. Why is it not `varchar`?

http://typeorm.io/#/entities/column-types-for-postgres

```
@Column("character varying",{ 
        nullable:false,
        length:255,
        primary:true, 
        })
    id:string;
        

    @Column("character varying",{ 
        nullable:true,
        length:255, 
        })
    title:string;
```

**Comment by Kononnable** [comment]
Standard postgres queries always display type as `character varying`. However since it is an alias of `varchar` shorter version is much more readable(at least for me).
Thanks for catching that up.
