### ISSUE TITLE
entity.mst doesn't include JoinTable name

### ISSUE THREAD

**Issue by baerrach** [Kononnable/typeorm-model-generator#151]
```
    {{#if isManyToMany}}@JoinTable(){{else}}@JoinColumn({ name:'{{ ../options/name}}'}){{/if}}{{/isOwner}}
```

The generator is able to detect that an @JoinTable should be used, and has correctly determined the relations, so the information is available.

If the name of the JoinTable doesn't match the defaults for TypeORM then there will be errors.

In our case our Join Tables are name `_A_B` instead of `A_B` as TypeORM expects.

For now my work around is to manually add them.

**Comment by Kononnable** [comment]
Fixed and released in typeorm-model-generator@0.3.2
