### ISSUE TITLE
Should not be overwriting tsconfig.json and ormconfig.json

### ISSUE THREAD

**Issue by niedfelj** [Kononnable/typeorm-model-generator#154]
Running this overwrote an existing tsconfig.json, littering the codebase with .js/.map files in addition to generating a new ormconfig.json that would override our existing ormconfig.yml setup. Why is it doing this?

**Comment by niedfelj** [comment]
I see now that there is a --noConfig flag. I would argue that this should be defaulted to "true"

**Comment by Kononnable** [comment]
I think adding it by default helps newcomers. It allow them to just start using typeorm because configs are already generated.
If someone wants to automate process of generating models they can still use `--noConfig`

**Comment by niedfelj** [comment]
Maybe you could change it to check if the files don’t exist already and at least give a warning or fail so it isn’t writing over stuff? I doubt most people are using this straight out of the box without having an existing TS install setup

**Comment by Kononnable** [comment]
Implemented in `typeorm-model-generator@0.4.4`
