### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by pairmix** [Kononnable/typeorm-model-generator#155]
Hi there,
A MongoDb support will be available ?

**Comment by Kononnable** [comment]
There is one problem with generating schema from mognoDb - schema is saved per row in a collection. So to get it right we would have to scan through every record in db. In most cases we would have to scan production data - we rarely test whole system, so some of the collections won't exist(or will be empty).

I'm not planning to implement MongoDb support anytime soon. After implementation this approach would take a lot of resources and generate a heavy load on a db server so there is a chance it wouldn't be usable on big dbs at all.
