### ISSUE TITLE
Allow disabling generation of OneToMany relations

### ISSUE THREAD

**Issue by Maia-Everett** [Kononnable/typeorm-model-generator#156]
Currently, the generator generates OneToMany relations for each table. It would be nice to be able to suppress that.

Incidentally, are they lazy by default?

**Comment by Kononnable** [comment]
> Currently, the generator generates OneToMany relations for each table.

I'm not sure what you mean - it should generate relations based on one already existing in db. Not sure why you would want to suppress it's generation.

>Incidentally, are they lazy by default?

There are two kinds of lazy relations in typeorm. Relations generated by default are lazy(they require user action to be loaded), but they don't use promises i.e you pass relation name to relations property in find options.
If you want use lazy properties with promises you have to pass `--lazy` parameter to the generator.
