### ISSUE TITLE
Escape entity column name in entity.mst template

### ISSUE THREAD

**Issue by flackenstein** [Kononnable/typeorm-model-generator#158]
I'm working with a mssql database that has a lot of table columns with poor naming conventions and results in a significant number of errors after generating the entitites.

A simple fix was to add quotes to the column name in the entity.mst template:  specifically around {{toPropertyName tsName}}

_{{printPropertyVisibility}}**"**{{toPropertyName tsName}}**"**:{{tsType}}{{#options/nullable}} | null{{/options/nullable}};_

This way if the database schema has columns that start with numbers, special characters it doesn't break JSON structure. 

Example: Wrapping column name in quotes...

    @Column("int",{ 
        nullable:true,
        name:"8038G"
        })
    "8038G":number | null;
        
This doesn't fix any relationship mapping issues, but cleans up most of the errors after generation.   This could be an edge case specific to my project but thought I would share.

**Comment by Kononnable** [comment]
I don't think it would help you much. You would still get model which is hard to use - you would have to access properties by using array notation etc.
Maybe try using custom naming strategy and adding a prefix to column names. This should also help with relationship mapping.
