### ISSUE TITLE
How to genergate @CreateDateColumn and @UpdateDateColumn?

### ISSUE THREAD

**Issue by NathanLi** [Kononnable/typeorm-model-generator#159]

**Comment by Kononnable** [comment]
It's not possible. `@CreateDateColumn` and `@UpdateDateColumn` columns are ORM-logic related so there is no easy way to decide which db columns should be marked as such in generated model. Developer can always change generated model and apply those decorators manually.

**Comment by NathanLi** [comment]
OK, I get it.  Thank you.
