### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by tkvw** [Kononnable/typeorm-model-generator#164]
I forked this project to make some improvements, but I have a couple of suggestions/questions: 
* A `CONTRIBUTING.MD` would be useful 
* A `.env.example` for the `docker-compose` configuration would be helpful 
* Where's the build target? 
* Is there a specific reason why there's no snapshot testing? I think it would be nice to actually test the generated output against expected output per db driver. The `EntityFileToJson` is limited in this use case.  

The issued I am investigating are: 
* When lazy option is active and relationId as well, the relationId is generated using a promise as well : 
```
@RelationId((user: User) => user.country)
countryId: Promise<string[]>;
```
* An include/exclude filter for tables

**Comment by Kononnable** [comment]
I will try to  add `CONTRIBUTTING.MD` and next time I have some more free time(probably next weekend).
For now I will paste my env file here: https://gist.github.com/Kononnable/fa3a2e1568d79c8d84ecd71271726d74

I've changed the build process recently to use ts-node, so there is no `outDir` with compiled js files. This change isn't published to npm yet. This is pure cli tool, so another dependency shouldn't be a problem and it should make development process easier.

What do you mean by snapshot testing? Comparing output files to entity files line by line? Generated files doesn't always have exactly the same output as input entities - e.g. there are index names for indices generated automatically by typeorm. I don't really like how `EntityFileToJson` works and I plan to change it in the future - to test not just generated entity files, but also internal object containing metadata information(which would allow to tests things like case converting, entity schemas model generation etc.).
