### ISSUE TITLE
Multiple values passed with separation of comma 

### ISSUE THREAD

**Issue by akashdathan** [Kononnable/typeorm-model-generator#166]
https://github.com/Kononnable/typeorm-model-generator/blob/b70aba10c8baa4e373e86d3e4fdd2ab464f351ae/src/index.ts#L105

It would be helpful to add this in the documentation. Had to look through the code base to figure it out. Thank you.

**Comment by CatsMiaow** [comment]
https://github.com/Kononnable/typeorm-model-generator/blob/master/README.md#usage
Seems to be a fixed issue
