### ISSUE TITLE
Generate models of multiple schemes in postgres

### ISSUE THREAD

**Issue by YeisonGomez** [Kononnable/typeorm-model-generator#175]
How can I generate the models of multiple schemes in postgres? Thanks in advance.

By the way, very good work with this

**Comment by YeisonGomez** [comment]
A comment in the object code resolved the doubt.

When generating the entities from the console where the schema is specified:

-s scheme1, scheme2, scheme3

Add it in the documentation please

**Comment by bertyhell** [comment]
PR created: https://github.com/Kononnable/typeorm-model-generator/pull/186
