### ISSUE TITLE
MSSql  precision is not added

### ISSUE THREAD

**Issue by m-kashif** [Kononnable/typeorm-model-generator#184]
When we are creating column with type numric(18,2)

it is generating the following and does not adding precision.

@Column("numeric",{
        nullable:true,
        scale:2,
        name:"basic_price"
        })
    basic_price:number | null;

And typeorm is treating scale:2 as precision instead of scale.

but when we manually add precision then its working fine...

@Column("numeric",{
        nullable:true,
        precision:18,
        scale:2,
        name:"basic_price"
        })
    basic_price:number | null;

**Comment by m-kashif** [comment]
We are facing same issue with type decimal as well...

**Comment by Kononnable** [comment]
Fixed and released in `typeorm-model-generator@0.3.5`.
