### ISSUE TITLE
How to increase the timeout 15000ms

### ISSUE THREAD

**Issue by javapad** [Kononnable/typeorm-model-generator#185]
How to increase the the timeout?

I need a 50000ms to complete.

https://github.com/Kononnable/typeorm-model-generator/issues/80

**Comment by javapad** [comment]
when Microsoft SQL
go to .../node_modules/type-orm-generator/node_modules/mssql
vi tedious.js
Line 209
cfg.options.requestTimeout = this.config.requestTimeout != null ? this.config.requestTimeout : 15000

change to 15000 to 50000

**Comment by Kononnable** [comment]
Implemented and released in `typeorm-model-generator@0.3.5` under `timeout` option.
