### ISSUE TITLE
Update dependencies and add access to more DB options

### ISSUE THREAD

**Issue by darkship** [Kononnable/typeorm-model-generator#188]
Hi,
**My problem:** 
my DB has nearly 700 tables and the column query (GetCoulmnsFromEntity) needs about 2mins to finish. But it breaks after 15s

To be able to use your model generator I need to increase the requestTimeout of the MSSQL ConnectionPool.

**Solution**
- Upgrade the outdated npm packages.
The MSSQL npm package will match the current documentation.
- make requestTimeout  (and other options?) accessible from your package.

This would also solve https://github.com/Kononnable/typeorm-model-generator/issues/185

Thank you.

**Comment by Kononnable** [comment]
Implemented and released in typeorm-model-generator@0.3.5 under timeout option(a month ago).
