### ISSUE TITLE
Older versions of oracle does not have IDENTITY_COLUMN

### ISSUE THREAD

**Issue by gintsgints** [Kononnable/typeorm-model-generator#195]
Identity column is feature introduced in version 12c.
https://oracle-base.com/articles/12c/identity-columns-in-oracle-12cr1

So with older versions of oracle you get:

(node:16704) UnhandledPromiseRejectionWarning: Error: ORA-00904: "IDENTITY_COLUMN": invalid identifier

While trying to extract.

Checking oracle version and automaticaly setting generated: false would imho help.

**Comment by semiautomatix** [comment]
Yes, having the same issue with 11g

**Comment by Kononnable** [comment]
Implemented in `typeorm-model-generator@0.4.0`
