### ISSUE TITLE
Proposal: update default naming strategy to CamelCase.

### ISSUE THREAD

**Issue by gintsgints** [Kononnable/typeorm-model-generator#196]
Hi,

I think it would be useful to update default naming strategy so Classes are named with CamelCase 
with Upper first letter, but field names as camelCase with Lower first letter.

If you agree, I am ready to make pull request for that.

Gints

**Comment by Kononnable** [comment]
Yeah, I think this is a great idea - many teams are using PascalCase for class names and camelCase for fields while those conventions might be completely different in database.

**Comment by gintsgints** [comment]
Sorry, my commit has build error. Probably somthing need to be changed in tests.

**Comment by Kononnable** [comment]
I will take a look once got some free time - probably on weekend. But I think changes to default parameters in `src/index.ts` would be sufficient and shouldn't be problematic.
