### ISSUE TITLE
MySQL Double column precision creates bad query

### ISSUE THREAD

**Issue by jayalfredprufrock** [Kononnable/typeorm-model-generator#197]
I've noticed that when a MySQL column is marked as `double` with no precision specified, the entity is generated with a default precision of 22 which ultimately translates to a query that looks something like like this: `fee double(22) NOT NULL`

This appears to be unsupported syntax, at least in MySQL 5.7. It looks like traditionally the precision has been of the format `double(M,D)` however it sounds like this format is deprecated as of v8.0.17 (https://dev.mysql.com/doc/refman/8.0/en/floating-point-types.html).

Other than this small snafu, this library has proven to be quite a time saver. Thanks for all your work!

**Comment by Kononnable** [comment]
Which typeorm-model-generator did you use to generate model without precision? Recently issue #184 was fixed which changed this behavior.

**Comment by jayalfredprufrock** [comment]
Yeah this was on 0.3.5, however I've investigated more and it seems that even TypeORM itself will generate migrations with this precision bug so now I'm not so sure this library is doing anything wrong. I'll go ahead and close the issue and reopen if I discover otherwise.

**Comment by scvgoe** [comment]
@jayalfredprufrock did you find any solution for it?

A precision option is only working with decimal type column in the typeorm,
so I think the generator generates the precision option only when a column type is decimal.

https://typeorm.io/#/entities
> precision: number - The precision for a decimal (exact numeric) column (applies only for decimal column), which is the maximum number of digits that are stored for the values. Used in some column types.
