### ISSUE TITLE
Question: How to add additional properties to column

### ISSUE THREAD

**Issue by NickClicknClear** [Kononnable/typeorm-model-generator#199]
The tool is working brilliantly for me, but there is one thing I can't work out how to do. 

I'd like to add a "select:false" to the column decorator for a password field so it doesn't get accidentally selected.

I can't work out how to do that without having to modify the source every time it's generated. 

Any suggestions?

**Comment by Kononnable** [comment]
The only thing that comes to my mind is to create a specific workflow. I'm in the process of writing a few examples of usage down, last to might be what you're looking for.
https://github.com/Kononnable/typeorm-model-generator/blob/ed500c612e88daaa60ae212677a5c86d873a4b29/USECASES.MD#git-repo-with-dependency-and-entire-pipeline

**Comment by NickClicknClear** [comment]
I'd rather avoid tweaking your code if I can. 

In some cases I've seen generators create base classes you shouldn't edit and then empty classes that extend the base classes so you can write modifications.

**Comment by Kononnable** [comment]
So I guess the best way would be, to change generated files every time and automate it(last approach from the link). There is no metadata to know which fields users would typically like to select, so library can't generate that.

I was thinking about implementing a feature which would allow us to preserve manually made changes to the generated code, but it's pretty complex one and I don't thing it will be implemented in the near future.
