### ISSUE TITLE
crlf line ending in the npm package

### ISSUE THREAD

**Issue by vujevits** [Kononnable/typeorm-model-generator#2]
The issue on macOS Sierra:
$ typeorm-model-generator
env: node\r: No such file or directory

caused by crlf (dos style) line terminators:
$ file /Users/vmark/.nvm/versions/node/v6.9.2/bin/typeorm-model-generator
/Users/vmark/.nvm/versions/node/v6.9.2/bin/typeorm-model-generator: a /usr/bin/env node script text executable, ASCII text, with CRLF line terminators

here is a related issue:
https://github.com/npm/npm/issues/13203

**Comment by Kononnable** [comment]
Please confirm if it is working now- I don't have macOS to test it.

**Comment by vujevits** [comment]
Yes it is working, thanks for your time.
