### ISSUE TITLE
broken entity code generated using with mysql datatype 'set'

### ISSUE THREAD

**Issue by godhelpjun** [Kononnable/typeorm-model-generator#200]
@Column("set",{ 
        nullable:false,
        name:"flag"
        })
    flag:;   //illegal syntax here in this line will cause tsc stop 

fa_category.ts(54,10): error TS1110: Type expected

**Comment by Kononnable** [comment]
Could you provide DDL statements to reproduce the issue?

**Comment by godhelpjun** [comment]
create table fruit(names set('apple','bananna','grape'));

**Comment by CatsMiaow** [comment]
https://github.com/Kononnable/typeorm-model-generator/issues/91

**Comment by Kononnable** [comment]
Duplicate of #91, lets keep this in one issue.
