### ISSUE TITLE
[POSTGRES] UNIQUE constraint resolved by @Index decorator

### ISSUE THREAD

**Issue by fbaldo31** [Kononnable/typeorm-model-generator#216]
### Description : 
When a table has a unique constraint it will be resolved as `@Index` decorator.

### Expected behaviour : 
It should be `@Unique` without `, {unique: true}`

[Official documentation](https://typeorm.io/#/decorator-reference/unique) 

---------------------------------------------------------------------------------

typeorm-model-generator version 0.3.5
PostgreSQL version 11
typeorm version 0.2.19

**Comment by Kononnable** [comment]
What do you mean by 'It should be'? It might be more readable to someone, but I think behavior will be same as current approach.

**Comment by Kononnable** [comment]
Closing as no response from the author.

**Comment by fbaldo31** [comment]
I meant that is the produced model currently is not usable. Replacing the decorator as i mentionned fix the bug. There is a chapter on the provided link to the official documentation describing the up-to-date way to decorate an UNIQUE CONSTRAINT
