### ISSUE TITLE
Relation IDs creates number array

### ISSUE THREAD

**Issue by NickClicknClear** [Kononnable/typeorm-model-generator#231]
If I set "--relationIds true"

I get relationIDs like:
`producerId!: number[];`

I think that this is wrong and it should be 
`producerId!: number;`

I think the problem is in line 37 in entity.mst
  `  {{printPropertyVisibility}}{{toPropertyName ../tsName}}Id{{strictMode}}: {{#if isOneToOne}}{{toLazy ../tsType}}{{else}}{{toLazy (concat  ../tsType "[]")}}{{/if}};{{/if}}{{/relations}}
`

Am I correct or am I missing something?

**Comment by Kononnable** [comment]
Sorry for the delay.

If you've got OneToOne relationship it should be `number`. If we've got ManyToMany relationship it should be `number[]` - for every entity A there are many entities B. For OneToMany - there should be `number` one one side and `number[]` on the other.

It looks like it is not working correctly for OneToMany/ManyToOne relationships.

**Comment by NickClicknClear** [comment]
Thanks for confirming appreciated.

**Comment by Kononnable** [comment]
It looks like this one was fixed long time ago. Should be working correctly (for some time).
