### ISSUE TITLE
Can I customize only file names?

### ISSUE THREAD

**Issue by CatsMiaow** [Kononnable/typeorm-model-generator#236]
I want to add the `*.entity.ts` suffix to the file while keeping the class name.
It would be nice if `entityFileName` was added to [NamingStrategy](https://github.com/Kononnable/typeorm-model-generator#naming-strategy).
`entityName` cannot change only the file name.

~~https://docs.nestjs.com/recipes/swagger#plugin~~
~~because there is `.entity.ts` in` dtoFileNameSuffix` in Nest swagger plugin.~~

~~https://docs.nestjs.com/techniques/database#repository-pattern~~
~~like the Photo class in the guide above - photo.entity.ts~~

https://github.com/Kononnable/typeorm-model-generator/blob/master/src/Engine.ts#L214
Alternatively, it would be nice to have the option to suffix the file name with the `.entity` suffix.

**Comment by danielrsantana** [comment]
Hi, do we have any update on this? it would be nice if the `NamingStrategy` allowed us to inform how we want to name our files as well.

**Comment by bhemala** [comment]
Hi, yes, it would be nice if the NamingStrategy allowed us to inform how we want to name our files as well. I would appriciate the ability to add the *.entity.ts suffix to the filename too.

**Comment by Kononnable** [comment]
Implemented in `typeorm-model-generator@0.4.4`

**Comment by codeslayer1** [comment]
Hey, can you please let me know the parameter that needs to be passed for file name suffix? Couldn't find it in help. Or do we need to create our own naming strategy file and pass it?

**Comment by CatsMiaow** [comment]
@codeslayer1
Please refer to https://github.com/CatsMiaow/node-nestjs-structure/blob/master/bin/NamingStrategy.js

**Comment by codeslayer1** [comment]
Hey, Thanks for the quick response. 

I referred to the link you shared and copied the file to `./NamingStrategy.js`. My file names are still generated using the default naming strategy.

Command
```
typeorm-model-generator -h host -d db -p 5432 -u user -x pass -e postgres -s public --cp snake --namingStrategy=./NamingStrategy
```

Logs
```
typeorm-model-generator@0.4.4-no-engines
[14:02:27] Starting creation of model classes.
[14:02:51] Using custom naming strategy for column names.
[14:02:51] Using custom naming strategy for entity names.
[14:02:51] Using custom naming strategy for relationId field names.
[14:02:51] Using custom naming strategy for relation field names.
[14:02:51] Using custom naming strategy for entity file names.
[14:02:51] Using custom pluralization method for OneToMany, ManyToMany relation field names.
[14:02:53] Typeorm model classes created.
```

Can you please check if I am doing something wrong here or there is some issue with the package version **0.4.4**

**Comment by CatsMiaow** [comment]
@codeslayer1
See https://github.com/CatsMiaow/node-nestjs-structure/blob/master/bin/entity.js#L41
Try adding a file extension.

**Comment by codeslayer1** [comment]
Already tried that but the issue still remains. Will take a fork of the package and try debugging the issue.

**Comment by codeslayer1** [comment]
I just created a fork and made a local copy of the package. Was able to pass the naming strategy with the local build. Not sure what's wrong with the one installed through npm. 

Though found out another issue. Naming strategy is applied in the `ModelCustomization` phase post which the cases are converted in the `ModelGeneration` phase due to which any suffixes in the file names are being converted into pascalCase(default). So `File.entity.ts` gets changed to `FileEntity.ts`. 

This can be handled by passing `convertCaseFile` to none and doing any case Conversions in the custom naming strategy but just wanted to point this out here so that it may help anyone else who stumble upon this issue.

**Comment by DiCrEn** [comment]
Hi, I have the same problem too. 
Passing the full path to the namingStrategy parameter I get it to read the file, but it also convert from `File.entity.ts` to `FileEntity.ts`
