### ISSUE TITLE
is there any way to generate model for tables without PK

### ISSUE THREAD

**Issue by saostad** [Kononnable/typeorm-model-generator#238]
I have a database that some tables don't have PK on it and I have no control on database design, is there any way to generate a model for tables without PK? 
I know in typeorm [Each entity must have at least one primary column](https://github.com/typeorm/typeorm/blob/master/docs/entities.md#primary-columns) but it's for save function but in my case, I just want to do SELECT query.
I was wondering maybe it can generate model for me and I manually add a primary key with multiple fields on the model to make it work.

**Comment by Kononnable** [comment]
Typeorm uses primary keys not just for saving records. 
As for the question - typeorm-model-generator will let you know that table doesn't have PK, but as I recall it will generate model for such table. You can make some columns as primary then and it should work with typeorm for selecting entities(if schema sync is disabled etc.).

**Comment by flaviox83** [comment]
Up to version 0.3.5 the model were generated, while in version 0.4.0 they are not generated.

**Comment by Kononnable** [comment]
Looks like I'm not able to reproduce this. I created simple table without PK, tomg throwed an error, but created models successfully. Could you share your db engine and (partial) schema(DDL statements) which isn't generated correctly?

I used postgres and such table:
```
CREATE TABLE public."Post" (
	id int4 NOT NULL,
	"type" varchar NOT NULL
);
```

**Comment by Kononnable** [comment]
Closing as no response from the author.
