### ISSUE TITLE
Models EOL: LF vs CRLF

### ISSUE THREAD

**Issue by pc3b3r** [Kononnable/typeorm-model-generator#240]
When I run the tests there is the following issue on `output/entities/*`: 
on Windows EOL = `\r\n` --> **CRLF**
on Linux EOL = `\n`--> **LF**

Would be nice to choose or force a default EOL otherwise all the time there is a new generation from a different OS it will overwrite the old model.

**Comment by Kononnable** [comment]
Sorry for late response.
This will solve your problem, but only partially. You would still have inconsistent line endings in your code which might cause errors with weird, cryptic error messages.

You should look for settings in your source control provider - like `core.autocrlf` for git. It would take care of all of CRLF/LF inconsistencies.

**Comment by Kononnable** [comment]
Released in `typeorm-model-generator@0.4.1`.
