### ISSUE TITLE
 UnhandledPromiseRejectionWarning: RequestError: USE statement is not supported to switch between databases. Use a new connection to connect to a different database.

### ISSUE THREAD

**Issue by Brian611** [Kononnable/typeorm-model-generator#243]
Trying to generate models from a mssql db

**Comment by Kononnable** [comment]
What's your db engine version? Something specific in your configuration?

**Comment by Kononnable** [comment]
Closing as no response from the author.

**Comment by Brian611** [comment]
Found the solution my apologies for not coming back to this.

The issue is azure sql 2019 does not support the use of USE.

So cloned the repo and remove USE. i did not make a pull request as this could be an issue for people on sql that depend on the USE syntax to switch dbs

**Comment by Brian611** [comment]
So please reopen. So you guys sort this out. You need to find a way to detect azure sql 2019 and put a condition on the code.

**Comment by DavidEngelmark87** [comment]
I also have issues with this problem and considering how popular Azure SQL is becoming it would be great if this issue is fixed.

@Brian611 Can you please describe what you changed to be able to run this against a Azure SQL database?

**Comment by Brian611** [comment]
@DavidEngelmark87 you can generate from this pull request if you cannot wait for a merge. Let me know if it worked as expected.

**Comment by Kononnable** [comment]
Released in `typeorm-model-generator@0.4.2`.
