### ISSUE TITLE
Table phase has no PK. Error occurred in typeorm-model-generator. typeorm-model-generator@0.4.0  node@v12.10.0

### ISSUE THREAD

**Issue by subodh92** [Kononnable/typeorm-model-generator#244]
I am using typeorm-model-generator to generate the models from old database of postgres and table  has primary key (table name is  phase) but it's showing error that "Table phase has no PK".

**Comment by Kononnable** [comment]
Can you provide schema(DDL queries) for the table? It would allow to reproduce the issue and I will be able to check why it doesn't see a PK.

**Comment by AlejandroQuirozHdz** [comment]
![image](https://user-images.githubusercontent.com/20984846/74983042-e65ceb00-53fa-11ea-811b-b42f18ff245b.png)

**Comment by Kononnable** [comment]
Closing as no response from the author.
