### ISSUE TITLE
Error: dlopen( ... sqlite3/lib/binding/node-v67-darwin-x64/node_sqlite3.node, 1): no suitable image found

### ISSUE THREAD

**Issue by dumasss163** [Kononnable/typeorm-model-generator#253]
I've tried on both windows and macOS, got the same problem that node_sqlite3 is not valid, which drives me crazy, any solution??? thanks..

OS: macOS High Sierra
Node env: NVM v0.33.8 && node v11.15.0
Command: `typeorm-model-generator -h **.**.53.4 -d *** -p 3306 -u *** -x ************ -e mariadb`

Error detail

```
samdembp:datapro sam$ typeorm-model-generator -h **.**.53.4 -d *** -p 3306 -u *** -x ************ -e mariadb
internal/modules/cjs/loader.js:857
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Users/sam/.nvm/versions/node/v11.15.0/lib/node_modules/typeorm-model-generator/node_modules/sqlite3/lib/binding/node-v67-darwin-x64/node_sqlite3.node, 1): no suitable image found.  Did find:
	/Users/sam/.nvm/versions/node/v11.15.0/lib/node_modules/typeorm-model-generator/node_modules/sqlite3/lib/binding/node-v67-darwin-x64/node_sqlite3.node: truncated mach-o error: segment __TEXT extends to 1896448 which is past end of file 195958
	/Users/sam/.nvm/versions/node/v11.15.0/lib/node_modules/typeorm-model-generator/node_modules/sqlite3/lib/binding/node-v67-darwin-x64/node_sqlite3.node: truncated mach-o error: segment __TEXT extends to 1896448 which is past end of file 195958
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:857:18)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/sam/.nvm/versions/node/v11.15.0/lib/node_modules/typeorm-model-generator/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
```

**Comment by iWinston** [comment]
Hi, I have the same problem as you.

And I solve this problem by reinstall node and reinstall typeorm-model-generator.

Maybe it is caused by the failing to download node-pre-gyp when installing typeorm-model-generator?

**Comment by Kononnable** [comment]
>Maybe it is caused by the failure to download node-pre-gyp when installing typeorm-model-generator?

Yes, this looks like the reason for the error. Node 11 is no longer supported, so there probably aren't any precompiled packages ready(and compilation during install might fail if you don't have the dependencies e.g. python). 
Anyhow, it is possible now to use typeorm-model-generator without preinstalled db drivers(use `no-engines` tag) in case there are any troubles with unneeded db drivers. https://github.com/Kononnable/typeorm-model-generator#versions

PS. You should not use node@11 anymore.
