### ISSUE TITLE
Creates entities for certain tables, but does not create an entity for some temporary tables.

### ISSUE THREAD

**Issue by spartiate480** [Kononnable/typeorm-model-generator#255]
This table did have an entity created:
[omsmobile_login.txt](https://github.com/Kononnable/typeorm-model-generator/files/4331256/omsmobile_login.txt)

This table is an example that did not have an entity created:
[ht_survey.txt](https://github.com/Kononnable/typeorm-model-generator/files/4331245/ht_survey.txt)

This is the problem table from the error below:
[export.txt](https://github.com/Kononnable/typeorm-model-generator/files/4331234/export.txt)

```
Table HT_SURVEY has no PK.
Error occurred in typeorm-model-generator.
typeorm-model-generator@0.4.1  node@v11.3.0
If you think this is a bug please open an issue including this log on https://github.com/Kononnable/typeorm-model-generator/issues
(node:26479) UnhandledPromiseRejectionWarning: SyntaxError: Argument expression expected. (21:21)
  19 | applicationUser:ApplicationUser;
  20 |
> 21 | @ManyToOne(()=>Case,case=>case.gisErrors)
     |                     ^
  22 | @JoinColumn([{ name: "CASE_ID", referencedColumnName: "caseId" },
  23 | ])
  24 |
    at t (/usr/lib/node_modules/typeorm-model-generator/node_modules/prettier/parser-typescript.js:1:347)
    at Object.parse (/usr/lib/node_modules/typeorm-model-generator/node_modules/prettier/parser-typescript.js:14:180461)
    at Object.parse (/usr/lib/node_modules/typeorm-model-generator/node_modules/prettier/index.js:9739:19)
    at coreFormat (/usr/lib/node_modules/typeorm-model-generator/node_modules/prettier/index.js:13252:23)
    at format (/usr/lib/node_modules/typeorm-model-generator/node_modules/prettier/index.js:13510:73)
    at formatWithCursor (/usr/lib/node_modules/typeorm-model-generator/node_modules/prettier/index.js:13526:12)
    at /usr/lib/node_modules/typeorm-model-generator/node_modules/prettier/index.js:44207:15
    at Object.format (/usr/lib/node_modules/typeorm-model-generator/node_modules/prettier/index.js:44226:12)
    at databaseModel.forEach.element (/usr/lib/node_modules/typeorm-model-generator/dist/src/ModelGeneration.js:60:36)
    at Array.forEach (<anonymous>)
(node:26479) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26479) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


```

**Comment by Kononnable** [comment]
`Table HT_SURVEY has no PK.` - and there is no Primary key defined in HT_SURVEY  table, so it won't be usable by typeorm anyhow. Real question is: should models be generated for temporary tables in general?

As for `export.txt` file - I don't see here any field named `CASE_ID` which is mentioned in error message.

**Comment by spartiate480** [comment]
That's true about temp tables. I'll add those manually as needed. So is
there a way to exclude certain tables? I've tried using the command that
lets you target tables to exclude but the connect string fails with that
command for some reason.

That could mitigate my issue.

**Comment by Kononnable** [comment]
There is no option to generate only specific tables(at least yet). Recently there was a change which should allow to continue generating models even if some of them contains errors. It isn't released yet, but you can install it from github repo. This will allow you to generate models for all of the tables and pick the ones you want manually.

**Comment by spartiate480** [comment]
Okay, that should work in this case. I'll pull that code and give it a try.
