### ISSUE TITLE
TYPO?: COLUMN_TYPE in MysqlDriver

### ISSUE THREAD

**Issue by Joniras** [Kononnable/typeorm-model-generator#262]
I was trying to generate Models for my Mysql Database when i encountered an error: 

``` error
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'substring' of undefined
    at XXX\node_modules\typeorm-model-generator\dist\src\drivers\MysqlDriver.js:210:68
```

Then i found out that everywhere is used the uppercase ATTRIBUTE (eg: CHARACTER_MAXIMUM_LENGTH), except for column_type:

dist/src/drivers/MysqlDriver.js:206-211
``` js
case "enum":
         colInfo.ts_type = "string";
         colInfo.sql_type = "enum";
         console.log(resp);
         colInfo.enumOptions = resp.column_type.substring(5, resp.column_type.length - 1).replace(/\'/gi, '"');
         break;
```

Changing the attribute `column_type` to uppercase resolves the issue (for me).

**Comment by Kononnable** [comment]
Please try updating `typeorm-model-generator`. I don't see any lowercase `column_type` in the current code. Line number from the error doesn't match either.

**Comment by Joniras** [comment]
Ok strange, appearently i had an old file in node_modules/node/bin called `typeorm-model-generator(.cmd|.exe)` that somehow blocked the updating of the package. 

## Solution 
Deleting all the files that are named in the above scheme. (I also used --force when installing)

Issue resolved, thanks.
