### ISSUE TITLE
How to create a specific entity by given a table name?

### ISSUE THREAD

**Issue by jasonyoung92** [Kononnable/typeorm-model-generator#263]
I'm a new for using typeorm-model-generator, and I want to find a way to generate a specific entity by using a given table name.

Is there a way we can do it now, or can you support this functionality in future?

Like, we have a table name `job`, and we want to generate Job entity by given a flag `-t job` and only generate this entity when give this flag.

**Comment by Kononnable** [comment]
No, there is no flag to generate only specific tables. For now you can generate all of the tables and just pick files with the ones you want(or add every other table to skipTables parameter).

**Comment by pupudu** [comment]
Hi @Kononnable 
Is there a chance to get this prioritised? Happy to send a PR.
Many thanks

**Comment by kennasoft** [comment]
Hi @Kononnable 

Thanks for this awesome utility. I'm using it for a REST API generation tool I'm building: https://www.npmjs.com/package/restalize. 

I'm with @pupudu. I'd like to contribute to this. I'm thinking it'd be an option like: 
```
-t, --tables <table-names-to-generate-entities-for>
```

**Comment by Kononnable** [comment]
Implemented in `typeorm-model-generator@0.4.3`
