### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:3308

### ISSUE THREAD

**Issue by Coachware-Admin** [Kononnable/typeorm-model-generator#267]
I am unable to run typeorm-model-generator from within one Docker Container to call a MySQL server that is running in another Docker Container.

I have a docker-compose.yml file that looks like this:
```
version: '3'

services:
    
    mysql-development:
        image: mysql:8.0.17
        environment:
            MYSQL_ROOT_PASSWORD: helloworld
            MYSQL_DATABASE: testapp
        ports:
        - "3308:3306"
        
    admin:    
        image: adminer    
        ports:      
        - "8080:8080"
   
```

I then run docker-compose up  and it starts up the container.

I can connect by opening a browser and going to localhost:8080

![image](https://user-images.githubusercontent.com/62471928/79046633-1a3ddb00-7c0a-11ea-9e4a-9cba5679c8a8.png)

I had tried to avoid installing anything locally but in the end I decided to install MySQL Workbench locally to check - and that connects correctly too:
![image](https://user-images.githubusercontent.com/62471928/79047117-a6e99880-7c0c-11ea-8f17-c4e61d8be873.png)

Once connected, I can run SQL scripts like this:
```
CREATE TABLE school (
 SchoolId INT NOT NULL AUTO_INCREMENT,
 Name VARCHAR(85) NOT NULL,
 PRIMARY KEY (SchoolId));
```
and
```
select * from school
```

My local development is done using Visual Studio, developing in a dev container.
I create a folder for my development ( _/sampleapp_ ) and in that folder I create a subfolder called .devcontainer.  In .devcontainer I have two files:

devcontainer.json
```
// For format details, see https://aka.ms/vscode-remote/devcontainer.json or this file's README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.107.0/containers/typescript-node-12
{
	"name": "Visual Studio Code Remote Containers",
	"dockerFile": "Dockerfile",

	// Use 'appPort' to create a container with published ports. If the port isn't working, be sure
    // your server accepts connections from all interfaces (0.0.0.0 or '*'), not just localhost.
	"appPort": [3080],
	
    // Comment out the next line to run as root instead.
    "remoteUser": "node",

    // Use 'settings' to set *default* container specific settings.json values on container create. 
    // You can edit these settings after create using File > Preferences > Settings > Remote.
	"settings": { 
		"terminal.integrated.shell.linux": "/bin/zsh"
	},

    // Specifies a command that should be run after the container has been created.
    "postCreateCommand": "yarn install",

	// Add the IDs of extensions you want installed when the container is created.
	"extensions": [
		"dbaeumer.vscode-eslint",
       	// Chrome debugger
		"msjsdiag.debugger-for-chrome",
		"ms-vscode.vscode-typescript-tslint-plugin",
		"CoenraadS.bracket-pair-colorizer",
		"Tyriar.sort-lines",
		"Orta.vscode-jest"
 	]

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [3070]
}
```

Dockerfile - consists of just one line:
```
FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:0-12
```

I open Visual Studio and (following [https://code.visualstudio.com/docs/remote/containers](https://code.visualstudio.com/docs/remote/containers)) I use the Visual Studio Code Remote - Containers extension to open that _/sampleapp_ folder in a container.

In Visual Studio, I open a new Terminal window and try to run
```
npx typeorm-model-generator -h localhost -p 3308 -d testapp -u root -x helloworld -e mysql -o .
```
but I get the error message: **connect ECONNREFUSED 127.0.0.1:3308**

I have tried changing localhost to 0.0.0.0 but to no avail either.

**Comment by Kononnable** [comment]
I'm not familiar with vscode container development, but I might have a clue on what's going on. You can try:
- change `localhost` to `host.docker.internal` - it will point to your machine(`localhost` from within a container points to same container)
- if(I don't know if this is working this way) vscode container is attached to network from your docker-compose file you should be able to reach db on `mysql-development:3306`
