### ISSUE TITLE
[MSSQL] Fail to connect  and no message

### ISSUE THREAD

**Issue by Jacen** [Kononnable/typeorm-model-generator#272]
When I try to connect it stays with this text, it doesn't show anything else.

```
typeorm-model-generator@0.4.2
[8:03:54] Starting creation of model classes.
tedious deprecated The default value for `config.options.enableArithAbort` will change from `false` to `true` in the next major version of `tedious`. Set the value to `true` or `false` explicitly to silence this message. ..\AppData\Roaming\npm\node_modules\typeorm-model-generator\node_modules\mssql\lib\tedious\connection-pool.js:61:23
```

**Comment by Kononnable** [comment]
It's just a warning of tedious dependency. Model should be generated correctly, but depending on server configuration and workload it might take a while.

**Comment by Jacen** [comment]
But it isn´t show any message.
I kept it runninb for a long time

**Comment by Kononnable** [comment]
Time may vary - it depends on schema complexity, server load etc. You can see in activity monitor if query run by model generator isn't blocked by any other session etc.
