### ISSUE TITLE
[POSTGRES] GENERATED ALWAYS AS IDENTITY doesn't get @PrimaryGeneratedColumn decorator 

### ISSUE THREAD

**Issue by garethhcoleman** [Kononnable/typeorm-model-generator#274]
Hiya - fantastic tool! Amazed at how much it seems to have extracted from my database... but...

I might be confused, but I generated this table in postgres:

`CREATE TABLE "address" (
  "addressId" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY);`

When running typeorm-model-generator with defaults, the resultant model had addressId like so:

`@Column("integer", { primary: true, name: "addressId" })
  addressId: number;`

As a beginner with type-orm, I was expecting

`@PrimaryGeneratedColumn({ name: "addressId" })
  addressId: number;`

I hope I've given enough detail to be clear / allow for reproduction but apologies if not, I can supply them naturally. Thanks in advance!

**Comment by Kononnable** [comment]
Implemented in `typeorm-model-generator@0.4.3`
