### ISSUE TITLE
Cannot set property EntityManager of #<Object> which has only a getter

### ISSUE THREAD

**Issue by sgentile** [Kononnable/typeorm-model-generator#276]
I am getting this error running the command

```
npx typeorm-model-generator -h localhost -d postgres -u postgres -x password -e postgres -o . -s public --ssl
```

**Comment by Kononnable** [comment]
Sorry for the delay I didn't have much time for OSS lately.
Could you add something which would allow others to reproduce the issue? DDL statements, database backup etc.
