### ISSUE TITLE
Unknown column type: enum

### ISSUE THREAD

**Issue by sagarppatil** [Kononnable/typeorm-model-generator#28]
SQL Dialect: MySQL v5.7.19
OS: MacOS High Sierra 10.13.2

Thank you for this lovely project! I just stumbled upon it today and I tried it against an existing database for which I had both hand cranked typeorm entities and the subsequent database and the output from the model.

One particular entity had an `enum` type which the tool is unable to handle. I simply get a log statement
```
[12:53:04] Starting creation of model classes.
Unknown column type:enum
Unknown column type:enum
[12:53:04] Typeorm model classes created.
```

**Comment by Kononnable** [comment]
Added basic support for enum types. I still have to think if there is a nice way for creating and naming typescript enums for such columns or passing enum definition to type system other way, so it can be checked while transpiling.
