### ISSUE TITLE
RelationIds should respect the 'case-property' option

### ISSUE THREAD

**Issue by Morreski** [Kononnable/typeorm-model-generator#280]
Hi,
In my current setup I don't really need to use TypeORM relationships helpers. I'd rather use "natural" columns instead.

This is the flags that I used to generate the entities:
```bash
--noConfig --cf none --cp none -o src/entities --relationIds --disablePluralization 
```

And this is a sample of what's generated:
```typescript
@Index("example_entity_pkey", ["id"], { unique: true })
@Entity("example_entity", { schema: "public" })
export class ExampleEntity {
  @PrimaryGeneratedColumn({ type: "integer", name: "id" })
  id: number;

  @Column("integer", { name: "example_field" })
  example_field: number;

  @ManyToOne(() => User, (user) => user.exampleEntity)
  @JoinColumn([{ name: "user_id", referencedColumnName: "id" }])
  user: User;

  @RelationId((example_entity: ExampleEntity) => example_entity.user)
  userId: number[];
}
```

What bothers me here is that the relation id is named `userId` despite the option `--cp none` in the command. I expected it to be identical to the column name in database (i.e `user_id`). Also, the generated type seems odd (`number[]` instead of `number`).

If you guys agree with me on the expected behavior I'd gladly work on a PR to apply the same naming convention for "relationIds" and column names.

Cheers,

**Comment by Kononnable** [comment]
Implemented in `typeorm-model-generator@0.4.4`
