### ISSUE TITLE
Use of SSL

### ISSUE THREAD

**Issue by mtabaj** [Kononnable/typeorm-model-generator#3]
Thank for your work.  I have a remote database that must be loaded with SSL, how can I declare it?
Marcos

**Comment by Kononnable** [comment]
Unfortunately I haven't got much time to develop this project lately. For now the only way is to make changes in code.

You can change connection options manually in `src/drivers`. Choose your db driver and edit `ConnectToServer()` method. It should be working after adding some connection options(depending on db driver).

I will try to get back to this issue in about 2-3 weeks.
