### ISSUE TITLE
Many to many relation support

### ISSUE THREAD

**Issue by blablameh** [Kononnable/typeorm-model-generator#30]
Hello @Kononnable ,

First of all many thanks for such a wonderful model generator. This really makes using typeorm with existing tables a breeze.

I was just wondering if there is a way to support a Many to Many relationship between two tables, lets say by specifying mapping/junction table with a command line parameter.
In such a case model for junction table may be skipped.

An example would be : 
My MSSQL db server has
Users table, Roles table, and a UserRoles table which acts as junction table maintains mapping between Users table and Roles table.
UserRoles table has foreign key relation with User via UserId in UserRoles and Id in User table. It also has foreign key relation with Role via RoleId in UserRoles and Id in Roles table
While generating schema, User table can Many to Many relation stating UserRoles table as junction table in users table and the generation of schema for junction table may be skipped

Please do let me know, if this feature is already there and I am missing it.
Thanks once again for this brilliant node module :+1:

**Comment by Kononnable** [comment]
No, there is no many to many support yet.

I don't think junction table list is a good idea. With big databases it would be pain to use it that way.
I think there could be CLI parameter to declare if we want to generate Many to Many relations in models. Such tables should be easy to find - always columns number equal to columns in primary keys of related tables(2 or more if composite primary key), all columns used in foreign keys etc.

**Comment by blablameh** [comment]
@Kononnable thanks a ton for the detailed reply.
I totally agree with the point that junction table list in case of a large database would be a pain.
Your approach to sorting this and adding Many to Many relations sounds superfine. :+1:

**Comment by JeongJun-Lee** [comment]
I also wait for the many-to-many support.

**Comment by Kononnable** [comment]
Basic ManyToMany relation support introduced in `typeorm-model-generator@0.2.12`. 

No composite primary keys support yet. 
I've added it without introducing new CLI parameter, because due to a bug tables with two ManyToOne Relations(which are now hidden behind ManyToMany) aren't generated correctly most of the times.

**Comment by Kononnable** [comment]
Support for composite keys in many to many relations introduced in `typeorm-model-generator@0.2.16`

**Comment by JeongJun-Lee** [comment]
Great!!!

**Comment by ezze** [comment]
> Support for composite keys in many to many relations introduced in `typeorm-model-generator@0.2.16`

@Kononnable Is it possible with many to one relations? Sorry for bringing an old topic but I am struggling to create composite primary keys in many to one relations with `typeorm-model-generator@0.4.6`.

If I have the following simple table:

```sql
create table facility_image
(
    facility_id integer not null references facility(id),
    image_id integer not null references image(id)
);
```

then `typeorm-model-generator` generates this:

```typescript
import { Entity, JoinColumn, ManyToOne } from "typeorm";
import { Image } from "./Image";
import { Facility } from "./Facility";

@Entity("facility_image")
export class FacilityImage {
  @ManyToOne(() => Image, (image) => image.facilityImages)
  @JoinColumn([{ name: "image_id", referencedColumnName: "id" }])
  image: Image;

  @ManyToOne(() => Facility, (facility) => facility.facilityImages)
  @JoinColumn([{ name: "facility_id", referencedColumnName: "id" }])
  facility: Facility;
}
```

If I improve SQL query to create a table like this:

```sql
create table facility_image
(
    facility_id integer not null references facility(id),
    image_id integer not null references image(id),
    primary key(facility_id, image_id)
);
```

then `typeorm-model-generator` doesn't create entity class at all.

I use `sqlite` database.
