### ISSUE TITLE
SQLite Unknown column type timestamp

### ISSUE THREAD

**Issue by albertcito** [Kononnable/typeorm-model-generator#305]
Unknown column type: timestamp  table name: user column name: created_at
Error occurred in typeorm-model-generator.
typeorm-model-generator@0.4.3  node@v12.16.3

**Comment by Kononnable** [comment]
What is type of this column(shown in some gui/from statements which creates it)? 
I don't see `timestamp` in types supported by sqlite databases in typeorm https://github.com/typeorm/typeorm/blob/f2ba9012fe4e851bc667dfdfedc3fd4af665d52b/src/driver/sqlite-abstract/AbstractSqliteDriver.ts#L77-L109

**Comment by albertcito** [comment]
ouch, you are right. It was my mistake to write [timestamp](https://github.com/albertcito/nodejs-web-typescript/blob/production/src/db/migrations/BaseTableColumns/columns.ts) instead datetime in my migrations). I was testing the library trying re-create the DB.
