### ISSUE TITLE
Query optimization

### ISSUE THREAD

**Issue by gongzhaohui** [Kononnable/typeorm-model-generator#312]
The SQL of function GetCoulmnsFromEntity is not performance so well while there is a large number of tables in DB.Because the counting in sub query is computed every row.
It is better to move the counting to a join clause.
The original:
`SELECT TABLE_NAME,TABLE_SCHEMA,COLUMN_NAME,COLUMN_DEFAULT,IS_NULLABLE,
        DATA_TYPE,CHARACTER_MAXIMUM_LENGTH,NUMERIC_PRECISION,NUMERIC_SCALE,
        COLUMNPROPERTY(object_id(CONCAT(TABLE_SCHEMA,'.', TABLE_NAME)), COLUMN_NAME, 'IsIdentity') IsIdentity,
        (SELECT count(*)
         FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
             inner join INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE cu
                 on cu.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
         where
             tc.CONSTRAINT_TYPE = 'UNIQUE'
             and tc.TABLE_NAME = c.TABLE_NAME
             and cu.COLUMN_NAME = c.COLUMN_NAME
             and tc.TABLE_SCHEMA=c.TABLE_SCHEMA) IsUnique
        FROM INFORMATION_SCHEMA.COLUMNS c
        where TABLE_SCHEMA in (${schema}) AND TABLE_CATALOG in (${MssqlDriver.escapeCommaSeparatedList(
                dbNames
            )})
             order by ordinal_position`

A solution: 
`SELECT c.TABLE_NAME,c.TABLE_SCHEMA,c.COLUMN_NAME,c.COLUMN_DEFAULT,IS_NULLABLE,
            DATA_TYPE,CHARACTER_MAXIMUM_LENGTH,NUMERIC_PRECISION,NUMERIC_SCALE,
            COLUMNPROPERTY(object_id(c.TABLE_SCHEMA + '.'+ c.TABLE_NAME),c. COLUMN_NAME, 'IsIdentity') IsIdentity,
            CASE WHEN ISNULL(tc.cnt,0)>0 THEN 1 ELSE 0 END AS  IsUnique
            FROM INFORMATION_SCHEMA.COLUMNS c
            LEFT JOIN
                (SELECT tc.TABLE_SCHEMA,tc.TABLE_NAME,cu.COLUMN_NAME,COUNT(1) AS cnt
                FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
                    inner join INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE cu
                        on cu.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
                where
                    tc.CONSTRAINT_TYPE = 'UNIQUE' GROUP BY tc.TABLE_SCHEMA,tc.TABLE_NAME,cu.COLUMN_NAME) AS tc
                 on tc.TABLE_NAME = c.TABLE_NAME
                 and tc.COLUMN_NAME = c.COLUMN_NAME
                 and tc.TABLE_SCHEMA=c.TABLE_SCHEMA
            where c.TABLE_SCHEMA in (${schema}) AND c.TABLE_CATALOG in (${MssqlDriver.escapeCommaSeparatedList(
                dbNames
            )})
             order by ordinal_position`

**Comment by Kononnable** [comment]
Not sure why previous version of query isn't optimized properly(simple correlated queries are sometimes optimized to form similar to second query). Anyway, thanks for catching that up.

**Comment by gongzhaohui** [comment]
I can`t illustrate it clearly.In my case ,there are 260K columns in the DB,and then original query hanged up,the 'solution' completed in 23s.

**Comment by Kononnable** [comment]
Similar results for me, I just thought mssql would optimize first query better. Applied changes,  new version will be released later this week

**Comment by gongzhaohui** [comment]
Great
