### ISSUE TITLE
Don't convert the column names to camelcase 

### ISSUE THREAD

**Issue by georgemickael-b** [Kononnable/typeorm-model-generator#315]
Is there any way to achieve this?

**Comment by georgemickael-b** [comment]
I figured it out going through the code.
typeorm-model-generator -h localhost -d test  -p 23306 -u admin -x password --cp none  -e mysql 

Please Document this. It is actually a crucial feature not documented.

**Comment by Kononnable** [comment]
There is no specific document with description of each and every option.
You can use `npx typeorm-model-generator --help` or wizard for short description of customization options.
