### ISSUE TITLE
When typeorm-model-generator decided to add number to fieldName?

### ISSUE THREAD

**Issue by wizardnet972** [Kononnable/typeorm-model-generator#319]
Why when I run `typeorm-model-generator` I get `2` added to the field name?

When I debug the source code I log the `databaseModel`:

In the picture you can see the `relations` have `fieldName` with value: `companyCd2`, it should be `companies`.

So my question is in which cases it adds a number to the field name?

![image](https://user-images.githubusercontent.com/4997825/103771089-c5f84800-502f-11eb-82ce-060ae090a97f.png)

**Comment by luiys** [comment]
how to solve this?

I'm having the following problem:

``` 
@Column("int", { name: "grupo", nullable: true })
 group: number | null; 
 
@ManyToOne(() => GrupoAcesso, (grupoAcesso) => grupoAcesso.grupoAcessoMenus, {
    onDelete: "NO ACTION",
    onUpdate: "NO ACTION",
})
@JoinColumn([{ name: "grupo", referencedColumnName: "id" }])
group2: GrupoAcesso;
```
  
  I just need the relation to be generated
  
 typeorm-model-generator version: 0.4.6
 database: mysql
