### ISSUE TITLE
For PostgreSQL library retrieves generator function names as defaults

### ISSUE THREAD

**Issue by jayarjo** [Kononnable/typeorm-model-generator#323]
Just tried this library and I have a question:

![Screen Shot 2021-01-15 at 1 04 07 PM](https://user-images.githubusercontent.com/150075/104704628-515d9180-5732-11eb-824b-175d39f13766.png)

Do you see the `default: () => "uuid_generate_v4()"`? Isn't meaningless? I mean how would one be able to use that in any meaningful way?

Maybe you should simply omit it? So when default isn't a value but rather a function - ignore it?

**Comment by Kononnable** [comment]
If you decide to recreate database using typeorm it should generate a column with default value generated by this sql function.
