### ISSUE TITLE
Column Comments

### ISSUE THREAD

**Issue by IonVillarreal** [Kononnable/typeorm-model-generator#327]
hi, is it possible to export column comments ?

**Comment by Kononnable** [comment]
Depends on what you mean by export. typeorm-model-generator supports column comments for database engines which support this feature in typeorm(mysql, mariadb).
https://github.com/Kononnable/typeorm-model-generator/blob/955d69478599b2e9196c68ed81d14010283bce24/test/integration/github-issues/93/entity/Post.ts#L19-L22
