### ISSUE TITLE
Cannot read property useUTC of undefined 

### ISSUE THREAD

**Issue by mercale** [Kononnable/typeorm-model-generator#328]
Is there a fix to below error? 

Environment: 
node: v14.15.4
npm/npx: v6.14.6

Step to reproduce:
$ npx typeorm-model-generator
typeorm-model-generator@0.4.4
? Choose database engine oracle
(node:40460) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'useUTC' of undefined
    at new OracleDriver (C:\Users\mercale\AppData\Roaming\npm-cache\_npx\40460\node_modules\typeorm-model-generator\node_modules\typeorm\driver\oracle\OracleDriver.js:162:26)

**Comment by Kononnable** [comment]
New version with fix will be released by end of the week. For now as a workaround you would have to downgrade typeorm version.

**Comment by denodaeus** [comment]
Downgrade to what version of typeorm?  I'm using ^0.2.29

**Comment by Kononnable** [comment]
Released in `typeorm-model-generator@0.4.5`.

What I mean was to change version of typeorm used by typeorm-model-generator(would require installing as dependency/cloning repo and doing manual change). Anyway, new version is released so workaround is no longer necessary.
