### ISSUE TITLE
typeorm-model-generator convert mysql bigint to string, is it the right way?

### ISSUE THREAD

**Issue by namleasia** [Kononnable/typeorm-model-generator#337]
It genereates entity column string from mysql bigint. I think it should be number instead of string. Am I wrong?
Example:
```typescript
@Column("bigint", {
    name: "my_field_name",
    nullable: true,
    comment: "some comment",
    default: () => "'0'",
  })
  myFieldName: string | null;
```
should be:
```typescript
@Column("bigint", {
    name: "my_field_name",
    nullable: true,
    comment: "some comment",
    default: () => "'0'",
  })
  myFieldName: number | null;
```

**Comment by Kononnable** [comment]
Some of `bigint` values doesn't fit js `Number` type. That's why `String` type is used - otherwise, you could lose your data. 
To address problems like this BigInt type was introduced recently to JS, but as far as I know, typeorm doesn't support it out of the box.

**Comment by porteron** [comment]
There could be a solution here using TypeScript. I use TypeOrm for NestJS a Typescript API Framework.

Maybe something like this would work, then you could use the `BigNumber` type instead of string.
```
import BigNumber from 'bignumber.js';

The typings declare a variable and a namespace both named BigNumber:

declare var BigNumber: BigNumber.BigNumberStatic;
export as namespace BigNumber;
```
