### ISSUE TITLE
Option for soft delete on entity

### ISSUE THREAD

**Issue by intrealm** [Kononnable/typeorm-model-generator#350]
Tyeporm allow softdelete and filters resultset when column decorated with @DeleteDateColumn

Currently, we have to manually change these column after running typeorm-model-generator.

Would be nice to have this option to check columns with deleatedAt columns and put this variable decorator as well.

Source : https://orkhan.gitbook.io/typeorm/docs/decorator-reference#deletedatecolumn

**Comment by Kononnable** [comment]
Feature may sound nice, however reality is harsh in the area.
Apart from name convention how to recognize @DeleteDateColumn from the database perspective? It's just a column, information about its special ussage is often not stored in db. Even if we find a way to find such columns there is no 'one way' of doing soft deleting between ORMs. Different column types are being used, in case of dates different timezones can be used(and timezone may not always be stored).

There are too many moving pieces for us to be able to recognize such columns without any doubt. Doing user transformation(search&replace) on generated model is a way to go here as user can validate if ORMs they use handle soft delete in a compatible way(e.g. column type, timezone) and easily recognize such columns based on their name convention.

**Comment by intrealm** [comment]
I understand the complications, but also I was thinking more of a CLI option something like --softDeleteColumnName=deletedAt, if this is not passed we don't do anything special.

Since there is a dependency on the model-generator in one of my projects, I had to use soft delete as well
So I have a script that runs the model-generator and the same script runs the code to search and replace with annotations/import.
