### ISSUE TITLE
Generated column type "string" is giving TS error

### ISSUE THREAD

**Issue by miltonhowe** [Kononnable/typeorm-model-generator#4]
I am using:
- typescript 2.5.2 
- typeorm 0.1.0-alpha.39
- mysql on Google cloud

When I generate the model, I get this typescript error on all my `varchar` columns, which it maps with type "string":

`@Column("string", {
				nullable: false,
				length: 10,
				primary: true,
				})
		reason_code: string;`

`TS2345:Argument of type '"string"' is not assignable to parameter of type '(type?: any) => Function'.`

A quick look at the typeorm source code leads me to guess that perhaps this script is out of date with typeorm.

I see no `string` type in `typeorm/driver/types/ColumnTypes.d.ts`. There are many which appear to be suitable as mapping to `varchar`:

`export declare type WithLengthColumnType = "int" | "tinyint" | "smallint" | "mediumint" | "bigint" | "character varying" | "varying character" | "nvarchar" | "character" | "native character" | "varchar" | "char" | "nchar" | "varchar2" | "nvarchar2" | "binary" | "varbinary";`

**Comment by Kononnable** [comment]
Unfortunately I haven't got much time to develop this project lately. 
I will get back to this issue in about 2-3 weeks. There will be special parameter for typeorm version(latest stable still use `string` type).

**Comment by Kononnable** [comment]
Should be fixed by 54fc6317d5701dd3fe78fa8edd5fd9b80b33682c. However some column types might not work properly until column recognition is rewritten to take advantage of changes in typeorm 0.1.
