### ISSUE TITLE
compossed PK not supported

### ISSUE THREAD

**Issue by papasconlimon** [Kononnable/typeorm-model-generator#46]
I try to create my models from a postgres database and i have a table with a PK compossed for two columns and the model generator get me this error:
"Table 'table' has no PK.
Fatal error occured."

PS: sorry for my bad english is not my mother language.

Thank you

**Comment by Kononnable** [comment]
Could you provide create statement for your table?

There is a test(`sample27`) which shows, that composite primary keys are working correctly, but probably not all cases are covered.

**Comment by papasconlimon** [comment]
@Kononnable 
This is my create statement for my table, it is initially created by EntityFrameword. 

`CREATE TABLE dbo."UsuariosEmpresas" (
	"EmpresaConexionID" int4 NOT NULL DEFAULT 0,
	"UsuarioID" int4 NOT NULL DEFAULT 0,
	CONSTRAINT "PK_dbo.UsuariosEmpresas" PRIMARY KEY ("EmpresaConexionID", "UsuarioID"),
	CONSTRAINT "FK_dbo.UsuariosEmpresas_dbo.EmpresaConexions_EmpresaConexionID" FOREIGN KEY ("EmpresaConexionID") REFERENCES "EmpresaConexions"("EmpresaConexionID") ON DELETE CASCADE,
	CONSTRAINT "FK_dbo.UsuariosEmpresas_dbo.Usuarios_UsuarioID" FOREIGN KEY ("UsuarioID") REFERENCES "Usuarios"("UsuarioID") ON DELETE CASCADE
)
WITH (
	OIDS=FALSE
) ;
CREATE INDEX "UsuariosEmpresas_IX_EmpresaConexionID" ON "UsuariosEmpresas" USING btree ("EmpresaConexionID") ;
CREATE INDEX "UsuariosEmpresas_IX_UsuarioID" ON "UsuariosEmpresas" USING btree ("UsuarioID") ;`

**Comment by Kononnable** [comment]
Should be fixed in `typeorm-model-generator@0.2.12`. 
Please let me know if you're still having issues after updating the package.
