### ISSUE TITLE
Is a Relational Integrity not supported yet?

### ISSUE THREAD

**Issue by JeongJun-Lee** [Kononnable/typeorm-model-generator#47]
Hello, at first, thank you for your great contribution.

Is this generator not likely to support relational integrity like cascadeUpdate or onDelete: "RESTRICT"? 
If so, it'll be new feature request.

**Comment by Kononnable** [comment]
Cascades are ORM functionality, so there is no possibility to choose programmatically which cascade option user wants. `onDelete` and `onUpdate` introduced in `typeorm-model-generator@0.2.15`
