### ISSUE TITLE
SQLITE support

### ISSUE THREAD

**Issue by SmetLeander** [Kononnable/typeorm-model-generator#49]
I'd like to convert my sqlite db to a typescript model.
When 'll this be possible?

Thanks in advance!

**Comment by Kononnable** [comment]
Probably 4-8 weeks. It's hard to tell how much free time I will be able to spend on developing this project and if some more important issues shows up in the meantime.

I didn't use SQLite before, but it looks pragma statements should be enough to generate model from existing database.

**Comment by Kononnable** [comment]
Implemented in `typeorm-model-generator@0.2.16`
