### ISSUE TITLE
Error: Table has no PK

### ISSUE THREAD

**Issue by randre70** [Kononnable/typeorm-model-generator#54]
```bash
typeorm-model-generator -h localhost -e postgres -u postgres -x postgres -d api -o . -s public
```
```bash
public
[08:46:59] Starting creation of model classes.
Table likes has no PK.
Fatal error occured.
typeorm-model-generator@0.2.11  node@v8.10.0
Fatal error occured in typeorm-model-generator.
If this is a bug please open an issue including this log on https://github.com/Kononnable/typeorm-model-generator/issues
 1: node::Abort() [node]
 2: 0x11e7759 [node]
 3: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
 4: 0xb79dac [node]
 5: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 6: 0x3f3d548042fd
Aborted (core dumped)
```

## Expected behavior
Log error message and continue exporting schema

## Postgres table script
CREATE TABLE public.likes
(
    entry_id uuid NOT NULL,
    user_id uuid NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    deleted_at timestamp(0) without time zone,
    CONSTRAINT uk_likes UNIQUE (entry_id, user_id)
)

**Comment by Kononnable** [comment]
TypeORM needs primary key on every table it uses. You should consider changing UNIQUE constraint to PRIMARY KEY constraint.

**Comment by randre70** [comment]
That's okay, but it would be great if the tool could just continue to generate the source code. A comment like TODO in the generated code would be helpful too.
The developer can continue with migrations...

**Comment by Kononnable** [comment]
I've changed that errors would now let model generation to continue. Generated model probably won't be working with typeorm(or with current state of database), but if errors are small someone might correct them manually.

Comments are only showed in console window. It would be hard to implement TODO comments in generated code with current generation process.

Thank you for suggestion.
