### ISSUE TITLE
why a unique constraint is generated as an index?

### ISSUE THREAD

**Issue by SilvestreBalboa** [Kononnable/typeorm-model-generator#57]
Hello, I would thank you for helping me.

I have a table T that has a unique constraint (associated with a column)
when I generated the entities, the unique constraint of this table is translated by the generator as a unique index: @Index ("uk_token", ["token",], {unique: true})

This is not correct because when I do the opposite (use this entity to generate a table in my DB with typeorm), the created table has an index and not a unique constraint like the original table T.

how to generate this constraint as a unique constraint with its name and not as an index?

**Comment by Kononnable** [comment]
Implemented in `typeorm-model-generator@0.2.13`
