### ISSUE TITLE
Add option to create an ID field

### ISSUE THREAD

**Issue by miltonhowe** [Kononnable/typeorm-model-generator#65]
When the entity has a foreign key, the generator creates a property for the foreign table as an entity, and then leaves out the id field which keyed to the foreign entity.
There should be an option to include both the foreign entity and the key from the original table. It would be nice as well if it could intelligently look for the `Id` suffix and remove and include it correctly.

For example:
```
@ManyToOne(type => User, consumerUserId => consumerUserId.listings, {nullable: false, onDelete: "NO ACTION", onUpdate: "NO ACTION"})
@JoinColumn({name: "consumer_user_id"})
consumerUser: User;

@Column("char", {
	name: "consumer_user_id",
	nullable: false,
	length: 255,
})
consumerUserId: string;
```

The `Id` gets chopped off for the Entity and included for the Id (here a string, sometimes an INT or other)

**Comment by Kononnable** [comment]
As for the removing of `Id` sufix: I was thinking for some time of more generic solution. I'm planing to implement something similar to typeorm custom naming strategy. Then removing `Id` sufix from relation names could be default behavior, but users would have the ability to change it if it doesn't suits theirs case.

**Comment by Maxpain177** [comment]
@Kononnable why this generator by default removes Id suffix?

**Comment by Kononnable** [comment]
Most of the time columns with this sufix are used only to relate two entities together. If you see a property(in typescript class) named `categoryId` you expect it type to be `number`, not `Category`. Default naming strategy remove this sufix because of such cases.
Just take a look at `sample2-one-to-one` in `/test/integration/examples/` if it's not clear.

**Comment by Maxpain177** [comment]
In our cases we often using user_id columns in selects. Using join to users table just for retreive id fields is stupid. Imho.

**Comment by Maxpain177** [comment]
Why not just add a parameter for this?

**Comment by Kononnable** [comment]
I'm think you're looking for `@RelationId` decorator.

As for joining tables just to get Id - most(not sure if every) of modern db drivers should generate query plan which won't touch related table.
