### ISSUE TITLE
Add option to include partial constructor

### ISSUE THREAD

**Issue by miltonhowe** [Kononnable/typeorm-model-generator#67]
I find myself adding this code to every single entity after I generate it:
```
export class Redemption {
	constructor(init?: Partial<Redemption>) {
		Object.assign(this, init);
	}
```

This allows you to use `const foo = new Redemption({foo: "bar"...});` to create entities.

**Comment by Kononnable** [comment]
Implemented in `typeorm-model-generator@0.2.16`
