### ISSUE TITLE
error installing in win 7 32 bit

### ISSUE THREAD

**Issue by sakar-sr** [Kononnable/typeorm-model-generator#70]
Hi,

I had an error installing on win 7 32 bit machine  

**Error Code:**
oracledb Beginning installation
oracledb Verifying installation
oracledb Continuing installation
oracledb ERR! NJS-054: Binary build/Release/oracledb.node was not installed.
oracledb ERR! Pre-built binary packages are not available for architecture="ia32"
oracledb ERR! Failed to install binary package oracledb-v2.2.0-node-v59-win32-ia32.gz
oracledb ERR! Error: HTTPS request for https://github.com/oracle/node-oracledb/r
eleases/download/v2.2.0/oracledb-v2.2.0-node-v59-win32-ia32.gz failed with code404
oracledb ERR! For help see https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting
npm ERR! code ELIFECYCLE
npm ERR! errno 87
npm ERR! oracledb@2.2.0 install: `node package/oracledbinstall.js`
npm ERR! Exit status 87
npm ERR!
npm ERR! Failed at the oracledb@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sakar\AppData\Roaming\npm-cache\_logs\2018-05-10T07_32_01_323Z-debug.log

**Comment by Kononnable** [comment]
Try `typeorm-model-generator@no-engines`. It won't install oracle and sqlite drivers. It's just a temporary workaround - removing all drivers will require some more code changes. It will probably work like typeorm in the future(installing drivers by hand).

**Comment by sakar-sr** [comment]
Thank you, I will try @no-engines flag.

**Comment by victorschinaider** [comment]
Same thing here in Ubuntu

**Comment by shaunc** [comment]
getting this on Mac OS with node 10.4
