### ISSUE TITLE
Try connection MongoDB: database name must be a string

### ISSUE THREAD

**Issue by clystian** [Kononnable/typeorm-model-generator#74]
Hi,
Trying run a generated project for mongodb, connection fails with message `MongoDB: database name must be a string`

a solution propose by @pleerock is about upgrading dependency: mongodb version: ^3.0.0
@alexbatis reports: *"when generating a project with the --express flag the default  version (as specified in package.json) was "^2.2.31"*

### Please update dependencies in generation tool

**[source]** https://github.com/typeorm/typeorm/issues/2180

Issue type:
[ * ] question
[ * ] bug report

Database system/driver:
[ * ] mongodb

TypeORM version:
[ * ] latest

Steps to reproduce or a small repository showing the problem:

Create a default project with command
```typeorm init --name test --database mongdb --express
cd test
yarn install
yarn start
```
You can see the following error :
```
{ MongoError: database name must be a string
     at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:31:11)
     at validateDatabaseName (/app/node_modules/mongodb/lib/db.js:1680:57)
     at new Db (/app/node_modules/mongodb/lib/db.js:156:3)
     at Db.db (/app/node_modules/mongodb/lib/db.js:1208:12)
     at MongoQueryRunner.getCollection (/app/src/driver/mongodb/MongoQueryRunner.ts:803:40)
     at MongoQueryRunner.<anonymous> (/app/src/driver/mongodb/MongoQueryRunner.ts:272:27)
     at step (/app/node_modules/typeorm/driver/mongodb/MongoQueryRunner.js:32:23)
     at Object.next (/app/node_modules/typeorm/driver/mongodb/MongoQueryRunner.js:13:53)
     at /app/node_modules/typeorm/driver/mongodb/MongoQueryRunner.js:7:71
     at new Promise (<anonymous>)
       name: 'MongoError',
       message: 'database name must be a string',
       driver: true }
```

My ormconfig.json file :
```
{
   "type": "mongodb",
   "database": "test",
   "synchronize": true,
   "logging": false,
   "entities": [
      "src/entity/**/*.ts"
   ],
   "migrations": [
      "src/migration/**/*.ts"
   ],
   "subscribers": [
      "src/subscriber/**/*.ts"
   ],
   "cli": {
      "entitiesDir": "src/entity",
      "migrationsDir": "src/migration",
      "subscribersDir": "src/subscriber"
   }
}
```

**Comment by Kononnable** [comment]
Sorry for the delay.
I'm not sure If I understand purpose of that issue. Typeorm-model-generator doesn't support generating models from mongodb databases, so there is no dependencies to update.

I think what @pleerock meant by 'update dependencies in generation tool' reffers to typeorm cli, not to typeorm-model-generator.

**Comment by pleerock** [comment]
@Kononnable yes right, I was referring to cli, not model generator.
