### ISSUE TITLE
Foreign key "Id" field mapped to the class instead of a number

### ISSUE THREAD

**Issue by secret-agent-B** [Kononnable/typeorm-model-generator#76]
I created 2 tables in postgres - issues and projects. Each issue would come from a project so there's a project id foreign key that exist in the issues table.
After running "typeorm-model-generator" instead of getting a projectId field in issues with type number, I get a projectId of type project.

@entity('Issue')
export class Issue {

@ManyToOne(type => Project, projectId => projectId.issues)
@JoinColumn({ name: 'projectId'})
projectId: Project; // this should be of type number and a new field called project should be created with type "project". 

...

**Comment by Kononnable** [comment]
I think this is same as #65. There are plans to implement that, but I didn't have time to do it yet.

**Comment by raime910** [comment]
Yep. If you point me to the the right direction I can make the change. Thank you for this great plugin btw. Makes our lives 10x easier.

**Comment by Kononnable** [comment]
I appreciate it, but right now it would be easier if I write it myself. I have pretty solid idea how to write it and explaining it would take some time. Also there is no developer guide(I have to write it someday) so setting up everything could take some time too.

I should have free time on weekend(finally) so basic(at least) naming strategy and few other issues should be implemented by the next week.

**Comment by raime910** [comment]
Ah OK. Thanks a bunch! I will wait for the new version.
