### ISSUE TITLE
Support schemas beside "public" for postgres version

### ISSUE THREAD

**Issue by chriszrc** [Kononnable/typeorm-model-generator#8]
It appears the generator is only able to see/looking for entities in the public schema, even if the default schema search_path includes other schemas. I had to recreate my tables in the public schema in order to model them. 

PS - but wow, what a time saver!!!

**Comment by chriszrc** [comment]
Yay!

**Comment by chriszrc** [comment]
Hmm, I just tried the latest version, and this doesn't seem to be working yet. Looks like there are other bug reports as well of people only being able to use entities in the public schema-

**Comment by Kononnable** [comment]
I've forgot to put schema information in generated ormconfig.json file. Models were generating correctly but typeorm didn't know to search for tables in different schema unless someone edited ormconfig manually.
In few days there will be new npm package version with these changes.
