### ISSUE TITLE
Can anyone explain how to implement my own NamingStrategy?

### ISSUE THREAD

**Issue by amfsyn** [Kononnable/typeorm-model-generator#90]
What I have done:
1) Download this repo as a zip file
2) Move it's unzipped contents to a directory in my project
3) Pass the path to NamingStrategy.ts into typeorm-model-generator

Result: 

> Error:
Cannot find module './typeorm-model-generator-copy/NamingStrategy.ts'

Same result if I omit the .ts.

This doesn't seem like the right way to be doing this, but I have no idea how else I should do it.

How do you make a NamingStrategy like the default one?

**Comment by walter211** [comment]
should not close, cause when u compile ts into js, the relative path of import wont change. Just give a better implementation psl
