### ISSUE TITLE
RelationInfo.isManyToOne error 

### ISSUE THREAD

**Issue by arild-haugstad** [Kononnable/typeorm-model-generator#94]
`RelationInfo.isManyToOne` currently checks for `relationType == "OneToOne"`; it should probably check for `relationType == "ManyToOne"`

https://github.com/Kononnable/typeorm-model-generator/blob/4a32d103a5e6637b487185187be2809943b1d538/src/models/RelationInfo.ts#L21-L23

**Comment by Kononnable** [comment]
Thanks for catching that up.
