### ISSUE TITLE
Oracle SID |  Support fo Oracle V11

### ISSUE THREAD

**Issue by destinatus** [Kononnable/typeorm-model-generator#95]
Error: ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

typeorm-model-generator.cmd -h <remote database>-p 1521  -u <user>-x <pass>-e oracle -o . -d <sid<>

**Comment by Kononnable** [comment]
It looks like incorrect database connection information are passed. There are missing values for host, user and password parameters. Check if you've configured oracle connection correctly(`tnsnames.ora`).

Parameters that works for me(may be some similarities with what you're looking for): `-h localhost -e oracle -d orclpdb1.localdomain -u typeorm_mg -x Passw0rd`

And one big favor to ask. If you want help write something, not just copy paste error message without any context. Pasting error in more issues won't help either(#1, #9). I guess the other issue has something to do with database engine version but again ... no context.

**Comment by destinatus** [comment]
I'm sorry.
I'm working. I can't give too much detail.
I'm working on Oracle 11g Enterprise.
This issue is fixed.

The other issue is outstanding.
typeorm-model-generator -h <ip> -p 1521 -d <service name> -u <user>-x <pwd> -e oracle -o .
[10:29:33] Starting creation of model classes.
(node:8492) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): Error: ORA-00904: "IDENTITY_COLUMN": invalid identifier
(node:8492) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

Identity column was introduced in oracle 12 and I'm in 11g.

**Comment by Kononnable** [comment]
According to typeorm/typeorm#2002 typeorm doesn't support oracle 11. Because of that there is no reason for typeorm-model-generator to support oracle 11(generated models couldn't be used either way).
If typeorm team decide to add compatibility for oracle 11 I will make changes to typeorm-model-generator.

**Comment by StetHD** [comment]
please open this case, I have two remote oracle 11g setup, for one of them it's working fine, for the other it gets ORA-00904
