### ISSUE TITLE
unexpected OneToOne relationship

### ISSUE THREAD

**Issue by irissoftworks** [Kononnable/typeorm-model-generator#97]
Let's say I have the following database schema:
```
User {
  id: uuid;
  name: varchar;
}
UserBalance {
  user_id: uuid; (fkey User)
  currency_id: uuid; (fkey Currency)
} 
Currency {
  id: uuid;
  code: varchar;
}
```
A user can have many balances, and the correct schema is generated with the balances being a OneToMany relationship.
Now, say I add the following unique index to the UserBalance table (as I want only one balance per currency):
`
Unique(["user_id", "currency_id"])
`
For some reason, this causes the balance to be generated as a one to one relationship with user, where database wise it's still clearly a one to many. I can still have an array of user_balance elements under the user, just with different currencies. 

I don't think that unique index should change the type of the relationship ?

**Comment by Kononnable** [comment]
Does your DDL statements looks like that? It generated ManyToMany relations for me.
What database engine and typeorm-model-generator version are you using?
```sql
CREATE TABLE public."Currency"
(
    id uuid NOT NULL,
    code character varying(20),
    CONSTRAINT currency_pkey PRIMARY KEY (id)
);
CREATE TABLE public."User"
(
    "Id" uuid NOT NULL,
    name character varying(20)[],
    CONSTRAINT "User_pkey" PRIMARY KEY ("Id")
);
CREATE TABLE public."UserBalance"
(
    user_id uuid NOT NULL,
    currency_id uuid NOT NULL,
    CONSTRAINT "UserBalance_pkey" PRIMARY KEY (user_id, currency_id),
    CONSTRAINT fk1 FOREIGN KEY (user_id)
        REFERENCES public."User" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk2 FOREIGN KEY (currency_id)
        REFERENCES public."Currency" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
CREATE UNIQUE INDEX ind
    ON public."UserBalance" USING btree
    (user_id, currency_id);
```

**Comment by Kononnable** [comment]
Closing as no answer from the reporter.
