### ISSUE TITLE
Join column with column name of 'foo_guid' converted to property 'fooGu'

### ISSUE THREAD

**Issue by ddura** [Kononnable/typeorm-model-generator#99]
For example, if I have a table that joins on a column o an entity and the name `foo_guid`, it seems that it is removing the `id` portion only and converting the name to `fooGu`. I assume it is explicitly looking for `id` at the end and just removing that.

**Comment by Kononnable** [comment]
Fixed by excluding guid column name endings. It should work well with most cases.

**Comment by Kononnable** [comment]
Fixed in `typeorm-model-generator@0.2.22`.
